[package]
name = "volt"
version = "2.0.3"
edition = "2021"
rust-version = "1.85.1"

[lib]
name = "volt"
crate-type = ["cdylib", "rlib"]
path = "volt/lib.rs"

[[bin]]
name = "volt"
path = "volt/volt.rs"

[[bin]]
name = "volt-probe"
path = "volt-probe/volt-probe.rs"

[dependencies]
libc = "0.2"
toml = "0.8"
ash = "=0.37.3"

[profile.release]
opt-level = 3
lto = "thin"
panic = "abort"
strip = true
