def get_dxvk_settings() -> dict:
    return {
        "_tab_metadata": (True,),
        "dxvk_hud": {
            "label": "HUD",
            "description": "Controls the DXVK in-game HUD overlay. Accepts a comma-separated list: devinfo, fps, frametimes, submissions, drawcalls, pipelines, descriptors, memory, allocations, gpuload, version, api, cs, compiler, samplers (D3D9), ffshaders (D3D9), swvp (D3D9). Additional modifiers: scale=x (e.g. 1.5), opacity=y (e.g. 0.5). Use '1' for devinfo+fps, 'full' for all elements.",
            "inputs": "1=basic (devinfo+fps), full=all elements, value=custom comma-separated list",
            "output": ("environment_variable", "DXVK_HUD", "", "", ""),
        },
        "dxvk_frame_rate": {
            "label": "Frame Rate Limit",
            "description": "Limit the frame rate. 0 uncaps the frame rate; any positive integer limits rendering to that many frames per second.",
            "inputs": "value=fps limit (e.g. 60), 0=off",
            "output": ("environment_variable", "DXVK_FRAME_RATE", "", "", ""),
        },
        "dxvk_filter_device_name": {
            "label": "Filter Device Name",
            "description": "Force DXVK to use a GPU whose Vulkan device name contains this substring. Useful on multi-GPU systems. If the substring matches more than one device, the first matched device is used.",
            "inputs": "value=device name substring (e.g. RX 7900)",
            "output": ("environment_variable", "DXVK_FILTER_DEVICE_NAME", "", "", ""),
        },
        "dxvk_filter_device_uuid": {
            "label": "Filter Device UUID",
            "description": "Force DXVK to use a specific GPU by its Vulkan device UUID. Must be a 32-character hexadecimal string with no dashes. Provides more precise selection than name filtering, especially with multiple identical GPUs.",
            "inputs": "value=32-char hex UUID (no dashes)",
            "output": ("environment_variable", "DXVK_FILTER_DEVICE_UUID", "", "", ""),
        },
        "dxvk_hdr": {
            "label": "HDR",
            "description": "HDR support. Exposes the HDR10 color space (DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020) to the application. Many games require this to be set to consider exposing HDR output.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "DXVK_HDR", "", "", ""),
        },
        "dxvk_config_file": {
            "label": "Config File Path",
            "description": "Override the path to the dxvk.conf configuration file.",
            "inputs": "value=filesystem path (e.g. /path/to/dxvk.conf)",
            "output": ("environment_variable", "DXVK_CONFIG_FILE", "", "", ""),
        },
        "dxvk_shader_cache": {
            "label": "Shader Cache",
            "description": "Control DXVK's internal shader cache. Set to 0 to turn it off entirely. Any caching would then have to be managed externally.",
            "inputs": "0=off",
            "output": ("environment_variable", "DXVK_SHADER_CACHE", "", "", ""),
        },
        "dxvk_shader_cache_path": {
            "label": "Shader Cache Path",
            "description": "Override the directory where DXVK stores internal shader cache files. Defaults to %LOCALAPPDATA%/dxvk on Windows or Wine, and $HOME/.cache or $XDG_CACHE_HOME on native Linux.",
            "inputs": "value=directory path",
            "output": ("environment_variable", "DXVK_SHADER_CACHE_PATH", "", "", ""),
        },
        "dxvk_frame_pace": {
            "label": "Frame Pace Mode (Low-Latency)",
            "description": "Frame pacing mode for dxvk-low-latency. 'low-latency' (default) combines high fps with low input lag and minimizes latency variance. 'max-frame-latency' matches upstream DXVK behavior and offers great visual smoothness. 'min-latency' prioritizes the absolute lowest latency at the cost of fps by stalling the GPU between frames. 'low-latency-vrr-X' (replace X with your monitor Hz, e.g. low-latency-vrr-240) adds VRR-aware v-blank timing to prevent additional v-sync buffering latency. Only effective with the dxvk-low-latency fork.",
            "inputs": "low-latency=low latency (default), max-frame-latency=upstream, min-latency=minimum latency, low-latency-vrr-240=vrr 240 Hz",
            "output": ("environment_variable", "DXVK_FRAME_PACE", "", "", ""),
        },
        "dxvk_state_cache": {
            "label": "State Cache (Sarek)",
            "description": "Control the DXVK-Sarek pipeline state cache. Set to 0 to turn off. This cache allows shaders to be recompiled ahead of time on subsequent runs, reducing stutter. Only applicable to DXVK-Sarek.",
            "inputs": "0=off",
            "output": ("environment_variable", "DXVK_STATE_CACHE", "", "", ""),
        },
        "dxvk_state_cache_path": {
            "label": "State Cache Path (Sarek)",
            "description": "Directory where DXVK-Sarek stores pipeline state cache files. Defaults to the current working directory of the application. Only applicable to DXVK-Sarek.",
            "inputs": "value=directory path",
            "output": ("environment_variable", "DXVK_STATE_CACHE_PATH", "", "", ""),
        },
        "dxvk_all_cores": {
            "label": "All Cores Shader Compilation (Sarek)",
            "description": "Use all available CPU cores for background shader compilation instead of the default half. May cause brief unresponsiveness during compilation bursts but can improve load times on CPUs that rely on all cores for throughput. Only applicable to DXVK-Sarek.",
            "inputs": "1=on",
            "output": ("environment_variable", "DXVK_ALL_CORES", "", "", ""),
        },
        "dxvk_dyasync_sarek": {
            "label": "Dyasync (Sarek)",
            "description": "Dynamic Asynchronous Pipeline Compilation in DXVK-Sarek. Dyasync reduces stuttering by compiling shader variants in the background and using a closest-match placeholder pipeline in the meantime. Disabling reverts to fully synchronous compilation. Only applicable to DXVK-Sarek.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "DXVK_DISABLE_DYASYNC", "", "", ""),
        },
        "ddraw_multi_threaded": {
            "label": "DDraw Multi-Threaded",
            "description": "Enforce the use of DDSCL_MULTITHREADED. Some games require multi-threaded DirectDraw access but don't request it themselves.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.forceMultiThreaded=", "", ";"),
        },
        "ddraw_swvp": {
            "label": "DDraw SWVP",
            "description": "Use Software Vertex Processing mode for all D3D9 devices (via the DDraw/D3D7 path).",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.forceSWVP=", "", ";"),
        },
        "ddraw_r3g3b2": {
            "label": "DDraw R3G3B2",
            "description": "Advertise support for the R3G3B2 (8-bit packed RGB) format. Needed by some older titles that require this format.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.supportR3G3B2=", "", ";"),
        },
        "ddraw_d16": {
            "label": "DDraw D16",
            "description": "Advertise support for the D16 depth format.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.supportD16=", "", ";"),
        },
        "ddraw_d24x8_for_d32": {
            "label": "DDraw D24X8 for D32",
            "description": "Replace any use of D32 depth format with D24X8. Workaround for games that request D32 but misbehave with it.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.useD24X8forD32=", "", ";"),
        },
        "ddraw_mask_8bit_modes": {
            "label": "DDraw Mask 8-bit Modes",
            "description": "Report any 8-bit display modes as being 16-bit. Works around games that enumerate 8-bit modes but can't actually handle palette rendering.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.mask8BitModes=", "", ";"),
        },
        "ddraw_pow2_textures": {
            "label": "DDraw POW2 Textures",
            "description": "Report power-of-two texture dimension restrictions to the application. Some older games rely on this cap being advertised.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.forcePOW2Textures=", "", ";"),
        },
        "ddraw_legacy_discard": {
            "label": "DDraw Legacy Discard",
            "description": "Respect DISCARD only on DYNAMIC + WRITEONLY buffers. Matches older DirectDraw behaviour at a small performance cost.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.forceLegacyDiscard=", "", ";"),
        },
        "ddraw_color_key_compatibility": {
            "label": "DDraw Color Key Compatibility",
            "description": "Circumvent the texelFetch color key shader path. Workaround for games whose color-keyed rendering breaks under the default path.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.colorKeyCompatibility=", "", ";"),
        },
        "ddraw_single_back_buffer": {
            "label": "DDraw Single Back Buffer",
            "description": "Map all back buffers onto a single D3D9 back buffer. Fixes games that create multi-buffer flip chains but don't handle them correctly.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.forceSingleBackBuffer=", "", ";"),
        },
        "ddraw_back_buffer_resize": {
            "label": "DDraw Back Buffer Resize",
            "description": "Resize the back buffer to screen size when needed. Helps with games that create undersized back buffers relative to the display mode.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.backBufferResize=", "", ";"),
        },
        "ddraw_back_buffer_write_back": {
            "label": "DDraw Back Buffer Write Back",
            "description": "Write back D3D9 back buffers during blits/locks on DDraw surfaces. Needed by games that read back from the back buffer on the CPU. Has a performance cost.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.backBufferWriteBack=", "", ";"),
        },
        "ddraw_depth_write_back": {
            "label": "DDraw Depth Write Back",
            "description": "Write back D3D9 depth stencils during blits/locks on DDraw surfaces. Needed by games that read back depth on the CPU. Has a performance cost.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.depthWriteBack=", "", ";"),
        },
        "ddraw_upload_depth_stencils": {
            "label": "DDraw Upload Depth Stencils",
            "description": "Upload depth stencils. Turning this off can reduce overhead for games that never read depth back, but breaks those that do.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.uploadDepthStencils=", "", ";"),
        },
        "ddraw_proxied_present": {
            "label": "DDraw Proxied Present",
            "description": "Blit back to the proxied flippable surface and present with DDraw. Compatibility path for titles that rely on DDraw-level presentation semantics.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.forceProxiedPresent=", "", ";"),
        },
        "ddraw_blit_on_flip": {
            "label": "DDraw Blit On Flip",
            "description": "Workaround that uses blits instead of flips for presentation. Fixes games where the flip path produces incorrect results or artifacts.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.forceBlitOnFlip=", "", ";"),
        },
        "ddraw_ignore_gamma_ramp": {
            "label": "DDraw Ignore Gamma Ramp",
            "description": "Ignore any application-set gamma ramp. Useful for games that set broken gamma on startup and leave the desktop looking wrong.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.ignoreGammaRamp=", "", ";"),
        },
        "ddraw_ignore_exclusive_mode": {
            "label": "DDraw Ignore Exclusive Mode",
            "description": "Force windowed-mode presentation even when the application requests EXCLUSIVE/FULLSCREEN. Helps with alt-tab and multi-monitor setups in legacy games.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.ignoreExclusiveMode=", "", ";"),
        },
        "ddraw_auto_gen_mip_maps": {
            "label": "DDraw Auto-Gen Mip Maps",
            "description": "Automatically generate all texture mip maps on the GPU. Adds mipmaps to games that don't provide them, at the cost of some memory and upload time.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.autoGenMipMaps=", "", ";"),
        },
        "ddraw_apitrace_mode": {
            "label": "DDraw APITrace Mode",
            "description": "All surface write-backs. Intended for debugging / apitrace capture. Comes with significant performance penalties.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.apitraceMode=", "", ";"),
        },
        "ddraw_emulate_fsaa": {
            "label": "DDraw Emulate FSAA",
            "description": "Use supported MSAA up to 4x to emulate FSAA on the DDraw/D3D7 path. 'true' applies emulation when the app requests FSAA; 'forced' applies it unconditionally; 'auto' (default) is off.",
            "inputs": "true=on, forced=force on, auto=off (default)",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.emulateFSAA=", "", ";"),
        },
        "ddraw_back_buffer_guard": {
            "label": "DDraw Back Buffer Guard",
            "description": "Determines how uploads for back buffer blits are handled. 'auto' (default) uses the standard guard path; 'strict' is a stricter path for games that read back the back buffer aggressively; 'disabled' turns the guard off.",
            "inputs": "auto=on (default), disabled=off, strict=strict path",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.backBufferGuard=", "", ";"),
        },
        "ddraw_max_available_memory": {
            "label": "DDraw Max Available Memory (MB)",
            "description": "Max available memory override for the DDraw/D3D7 path, shared with the D3D9 backend. Value in megabytes.",
            "inputs": "value=megabytes",
            "output": ("environment_variable", "DXVK_CONFIG", "ddraw.maxAvailableMemory=", "", ";"),
        },
        "d3d8_scale_dref": {
            "label": "D3D8 Scale Dref",
            "description": "Some early D3D8 games expect Dref (depth texcoord Z) to be on the range [0..2^bitDepth - 1]. This option scales it back to [0..1] in DXSO and fixed vertex function.",
            "inputs": "value=bitDepth (typically 24), 0=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d8.scaleDref=", "", ";"),
        },
        "d3d8_dref_scaling": {
            "label": "D3D8 Dref Scaling (Low-Latency)",
            "description": "Low-latency fork name for d3d8.scaleDref. Some early D3D8 games expect Dref on range [0..2^bitDepth - 1]; scales it back to [0..1].",
            "inputs": "value=bitDepth (typically 24), 0=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d8.drefScaling=", "", ";"),
        },
        "d3d8_shadow_perspective_divide": {
            "label": "D3D8 Shadow Perspective Divide",
            "description": "Older applications designed for Nvidia hardware (or Xbox ports) expect shadow map texture coordinates to be perspective divided even though D3DTTFF_PROJECTED is never set. Forces D3DTTFF_PROJECTED for necessary stages when a depth texture is bound to slot 0.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d8.shadowPerspectiveDivide=", "", ";"),
        },
        "d3d8_vs_decl": {
            "label": "D3D8 VS Decl",
            "description": "Some games rely on undefined behavior by using undeclared vertex shader inputs. Modifies vertex shader declaration. Comma-separated list of colon-separated number pairs (D3DVSDE_REGISTER:D3DVSDT_TYPE).",
            "inputs": "value=e.g. '0:2,3:2,7:1' for float3 pos/normal/uv",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d8.forceVsDecl=", "", ";"),
        },
        "d3d8_batching": {
            "label": "D3D8 Draw Call Batching",
            "description": "Specialized drawcall batcher for games that draw a lot of similar geometry in separate drawcalls (sometimes one triangle at a time). May hurt performance or introduce graphical artifacts outside of specific games known to benefit.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d8.batching=", "", ";"),
        },
        "d3d8_place_p8_in_scratch": {
            "label": "Place P8 in Scratch",
            "description": "P8 texture support workaround. Early Nvidia (GeForce 4) and ATI/AMD GPUs exposed P8 support; it was dropped in later cards. Places all P8 textures in D3DPOOL_SCRATCH so creation is guaranteed to succeed even if the format is unsupported. Helps older titles that don't handle the lack of P8 support.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d8.placeP8InScratch=", "", ";"),
        },
        "d3d8_legacy_discard": {
            "label": "D3D8 Legacy Discard",
            "description": "Older applications may rely on D3DLOCK_DISCARD being ignored for everything except D3DUSAGE_DYNAMIC + D3DUSAGE_WRITEONLY buffers. This approach incurs a performance penalty.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d8.forceLegacyDiscard=", "", ";"),
        },
        "d3d9_defer_surface_creation": {
            "label": "D3D9 Defer Surface Creation",
            "description": "D3D9 variant of deferSurfaceCreation. Create the VkSurface on the first Present call rather than at swap chain creation.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.deferSurfaceCreation=", "", ";"),
        },
        "d3d9_max_frame_latency": {
            "label": "D3D9 Max Frame Latency",
            "description": "D3D9 variant of maxFrameLatency. Enforce a stricter maximum frame latency. Setting this to 0 has no effect.",
            "inputs": "value=0-16",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.maxFrameLatency=", "", ";"),
        },
        "d3d9_max_frame_rate": {
            "label": "D3D9 Max Frame Rate",
            "description": "D3D9 variant of maxFrameRate. Same semantics as dxgi.maxFrameRate.",
            "inputs": "n=limit to n fps, 0=default, -1=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.maxFrameRate=", "", ";"),
        },
        "d3d9_custom_device_id": {
            "label": "D3D9 Custom Device ID",
            "description": "D3D9 variant of customDeviceId. Override the PCI device ID reported to the application.",
            "inputs": "value=four-digit hex",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.customDeviceId=", "", ";"),
        },
        "d3d9_custom_vendor_id": {
            "label": "D3D9 Custom Vendor ID",
            "description": "D3D9 variant of customVendorId. Override the PCI vendor ID reported to the application.",
            "inputs": "value=four-digit hex",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.customVendorId=", "", ";"),
        },
        "d3d9_custom_device_desc": {
            "label": "D3D9 Custom Device Description",
            "description": "Override the reported device description string for D3D9.",
            "inputs": "value=any string",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.customDeviceDesc=", "", ";"),
        },
        "d3d9_hide_nvidia_gpu": {
            "label": "D3D9 Hide Nvidia GPU",
            "description": "Report Nvidia GPUs as AMD GPUs for D3D8/9. Generally only done for games known to take issue with NVAPI or otherwise behave poorly on Nvidia.",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.hideNvidiaGpu=", "", ";"),
        },
        "d3d9_hide_nvk_gpu": {
            "label": "D3D9 Hide NVK GPU",
            "description": "D3D9 variant. Report Nvidia GPUs running on NVK as AMD GPUs.",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.hideNvkGpu=", "", ";"),
        },
        "d3d9_hide_amd_gpu": {
            "label": "D3D9 Hide AMD GPU",
            "description": "D3D9 variant. Report AMD GPUs as Nvidia GPUs for games with AMD-specific issues.",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.hideAmdGpu=", "", ";"),
        },
        "d3d9_hide_intel_gpu": {
            "label": "D3D9 Hide Intel GPU",
            "description": "Report Intel GPUs as AMD GPUs for D3D8/9. Defaults to True to circumvent iGPU-specific restrictions affecting early Intel hardware.",
            "inputs": "True=on (default), False=off, Auto=auto",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.hideIntelGpu=", "", ";"),
        },
        "d3d9_num_back_buffers": {
            "label": "D3D9 Num Back Buffers (Low-Latency)",
            "description": "D3D9 equivalent of numBackBuffers. Low-latency fork only.",
            "inputs": "value>=2, 0=no override",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.numBackBuffers=", "", ";"),
        },
        "d3d9_present_interval": {
            "label": "D3D9 Present Interval (Vsync)",
            "description": "D3D9 equivalent of syncInterval. 0=off entirely, positive=repeat image, negative=app default.",
            "inputs": "n=repeat n times, 0=off, -1=app default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.presentInterval=", "", ";"),
        },
        "d3d9_tear_free": {
            "label": "D3D9 Tear Free (Low-Latency)",
            "description": "D3D9 equivalent of dxvk.tearFree. True=mailbox present mode when vsync off; False=relaxed FIFO when vsync on. Low-latency fork only.",
            "inputs": "True=mailbox, False=relaxed fifo, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.tearFree=", "", ";"),
        },
        "d3d9_sampler_anisotropy": {
            "label": "D3D9 Sampler Anisotropy",
            "description": "D3D9 equivalent of d3d11.samplerAnisotropy. Override AF for all samplers.",
            "inputs": "value=0-16, 0=off, -1=app default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.samplerAnisotropy=", "", ";"),
        },
        "d3d9_sampler_lod_bias": {
            "label": "D3D9 Sampler LOD Bias",
            "description": "D3D9 equivalent of samplerLodBias. Added to app-provided bias.",
            "inputs": "value=-2.0 to 1.0",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.samplerLodBias=", "", ";"),
        },
        "d3d9_clamp_negative_lod_bias": {
            "label": "D3D9 Clamp Negative LOD Bias",
            "description": "D3D9 equivalent of clampNegativeLodBias.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.clampNegativeLodBias=", "", ";"),
        },
        "d3d9_sample_rate_shading": {
            "label": "D3D9 Sample Rate Shading",
            "description": "D3D9 equivalent of forceSampleRateShading.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.forceSampleRateShading=", "", ";"),
        },
        "d3d9_invariant_position": {
            "label": "D3D9 Invariant Position (Low-Latency)",
            "description": "D3D9 equivalent of invariantPosition. Low-latency fork only.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.invariantPosition=", "", ";"),
        },
        "d3d9_reproducible_command_stream": {
            "label": "D3D9 Reproducible Command Stream",
            "description": "D3D9 equivalent of reproducibleCommandStream.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.reproducibleCommandStream=", "", ";"),
        },
        "d3d9_shader_model": {
            "label": "D3D9 Shader Model",
            "description": "Shader model reported in device capabilities. Limited to 1 for D3D8 applications.",
            "inputs": "3=SM3, 2=SM2, 1=SM1, 0=fixed-function",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.shaderModel=", "", ";"),
        },
        "d3d9_evict_managed_on_unlock": {
            "label": "Evict Managed on Unlock (Low-Latency)",
            "description": "Evict managed resources from system memory when they are unlocked entirely. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.evictManagedOnUnlock=", "", ";"),
        },
        "d3d9_dpi_aware": {
            "label": "D3D9 DPI Aware",
            "description": "Whether to call SetProcessDPIAware on device creation. Helps avoid upscaling blur in modern Windows on Hi-DPI screens.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.dpiAware=", "", ";"),
        },
        "d3d9_strict_constant_copies": {
            "label": "Strict Constant Copies (Low-Latency)",
            "description": "Always copy defined constants to the UBO when relative addressing is used, rather than only when the relative addressing starts a defined constant. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.strictConstantCopies=", "", ";"),
        },
        "d3d9_strict_pow": {
            "label": "Strict Pow (Low-Latency)",
            "description": "Use opSelect for handling pow(0,0) = 0; otherwise it becomes undefined. Low-latency fork only.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.strictPow=", "", ";"),
        },
        "d3d9_lenient_clear": {
            "label": "D3D9 Lenient Clear",
            "description": "Whether to fastpath clear anyway when close enough to clearing a full render target.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.lenientClear=", "", ";"),
        },
        "d3d9_max_available_memory": {
            "label": "D3D9 Max Available Memory (MB)",
            "description": "Max initial value used in tracking and GetAvailableTextureMem. Value in megabytes.",
            "inputs": "value=megabytes (default 4096)",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.maxAvailableMemory=", "", ";"),
        },
        "d3d9_memory_track_test": {
            "label": "D3D9 Memory Track Test",
            "description": "Memory tracking test mode for d3d9.maxAvailableMemory.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.memoryTrackTest=", "", ";"),
        },
        "d3d9_float_emulation": {
            "label": "D3D9 Float Emulation",
            "description": "Force float point quirk emulation (anything * 0). True=faster but less accurate (good enough for most games). False=off entirely. Strict=slower but more correct (needed for some games). Auto=DXVK picks.",
            "inputs": "True=fast, Strict=accurate, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.floatEmulation=", "", ";"),
        },
        "d3d9_dialog_mode": {
            "label": "Dialog Mode (Low-Latency)",
            "description": "Change the default state of dialog box mode. Disables exclusive fullscreen when active. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.enableDialogMode=", "", ";"),
        },
        "d3d9_swapchain_msaa": {
            "label": "Swapchain MSAA (Low-Latency)",
            "description": "Override the application's MSAA level on the swapchain. Low-latency fork only.",
            "inputs": "value=0-16, -1=app default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.forceSwapchainMSAA=", "", ";"),
        },
        "d3d9_long_mad": {
            "label": "D3D9 Long Mad (Low-Latency)",
            "description": "Make Mads as FFma or as a long FMul+FAdd. Solves rendering bugs in games that have z-pass shaders which don't match the regular vertex shader. Low-latency fork only.",
            "inputs": "True=long, False=ffma (default)",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.longMad=", "", ";"),
        },
        "d3d9_alpha_test_wiggle_room": {
            "label": "Alpha Test Wiggle Room (Low-Latency)",
            "description": "Workaround for games using alpha test == 1.0 etc. due to wonky interpolation or miscellaneous imprecision on some vendors. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.alphaTestWiggleRoom=", "", ";"),
        },
        "d3d9_device_local_constant_buffers": {
            "label": "Device Local Constant Buffers",
            "description": "Use device local, host accessible memory for D3D9 constant buffers. Tends to be slower on AMD and same performance on Nvidia.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.deviceLocalConstantBuffers=", "", ";"),
        },
        "d3d9_explicit_front_buffer": {
            "label": "Explicit Front Buffer (Low-Latency)",
            "description": "Front buffer usage. Low-latency fork only.",
            "inputs": "False=on (default), True=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.noExplicitFrontBuffer=", "", ";"),
        },
        "d3d9_df_formats": {
            "label": "DF Formats",
            "description": "Support vendor extension DF floating point depth formats on AMD and Intel. Ignored and off on Nvidia (or when spoofing Nvidia) as it does not support these formats natively.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.supportDFFormats=", "", ";"),
        },
        "d3d9_d32_for_d24": {
            "label": "D32f for D24",
            "description": "Useful for reproducing AMD issues on other hardware.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.useD32forD24=", "", ";"),
        },
        "d3d9_x4r4g4b4": {
            "label": "X4R4G4B4",
            "description": "Support the X4R4G4B4 format. The Sims 2 is a very broken game.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.supportX4R4G4B4=", "", ";"),
        },
        "d3d9_d32": {
            "label": "D32 (Low-Latency)",
            "description": "Support the D32 format. Low-latency fork only.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.supportD32=", "", ";"),
        },
        "d3d9_a8rt": {
            "label": "A8 Render Target",
            "description": "Support for A8 format render targets. The Sims 2 is a very broken game.",
            "inputs": "False=on (default), True=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.disableA8RT=", "", ";"),
        },
        "d3d9_vcache": {
            "label": "VCache Query (Low-Latency)",
            "description": "Support for the vcache query. Not very important as a user config — used internally. Defaults to True if vendorId == 0x10de. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.supportVCache=", "", ";"),
        },
        "d3d9_sampler_type_spec_constants": {
            "label": "Sampler Type Spec Constants",
            "description": "Useful if games use the wrong image and sampler type combo (e.g. Halo: CE, Spellforce). Can fix rendering in older, broken games.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.forceSamplerTypeSpecConstants=", "", ";"),
        },
        "d3d9_aspect_ratio": {
            "label": "Aspect Ratio",
            "description": "Only expose modes with the given aspect ratio. Useful for titles that break if they see ultra-wide.",
            "inputs": "value=ratio (e.g. 16:9, 4:3)",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.forceAspectRatio=", "", ";"),
        },
        "d3d9_refresh_rate": {
            "label": "D3D9 Refresh Rate",
            "description": "D3D9 equivalent of dxgi forceRefreshRate. USE WITH CAUTION. Do not report issues.",
            "inputs": "value=Hz, 0=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.forceRefreshRate=", "", ";"),
        },
        "d3d9_mode_count_compatibility": {
            "label": "D3D9 Mode Count Compatibility",
            "description": "Aggressively limit the advertised mode count to only the current desktop resolution and refresh rate plus a minimal fallback list. Useful for titles like AquaNox that break with too many reported modes. Can combine with forceAspectRatio and forceRefreshRate.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.modeCountCompatibility=", "", ";"),
        },
        "d3d9_do_not_wait": {
            "label": "Do Not Wait (Low-Latency)",
            "description": "Allow the do not wait lock flag to be used. Useful if some apps use this incorrectly. Low-latency fork only.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.allowDoNotWait=", "", ";"),
        },
        "d3d9_discard": {
            "label": "Discard (Low-Latency)",
            "description": "Allow the discard lock flag to be used. Useful if some apps use this incorrectly. Low-latency fork only.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.allowDiscard=", "", ";"),
        },
        "d3d9_enumerate_by_displays": {
            "label": "D3D9 Enumerate By Displays",
            "description": "Whether to enumerate D3D9 adapters by display (Windows behaviour) or by physical adapter. May be useful in PRIME setups.",
            "inputs": "True=by display (default), False=by adapter",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.enumerateByDisplays=", "", ";"),
        },
        "d3d9_cached_write_only_buffers": {
            "label": "D3D9 Cached Write-Only Buffers",
            "description": "Allocate write-only resources in D3DPOOL_DEFAULT in cached system memory rather than uncached or host-visible VRAM, to allow fast CPU readback. Only useful for buggy applications; may reduce GPU-bound performance.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.cachedWriteOnlyBuffers=", "", ";"),
        },
        "d3d9_cached_dynamic_buffers": {
            "label": "D3D9 Cached Dynamic Buffers (Low-Latency / APITrace Mode)",
            "description": "Allocate dynamic resources in D3DPOOL_DEFAULT in cached system memory rather than uncached or host-visible VRAM, to allow fast CPU readback. Only useful for buggy applications; may reduce GPU-bound performance. Low-latency fork only (upstream uses cachedWriteOnlyBuffers).",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.cachedDynamicBuffers=", "", ";"),
        },
        "d3d9_seamless_cubes": {
            "label": "D3D9 Seamless Cubes",
            "description": "Don't use non-seamless cube maps even if supported. Non-seamless is correct D3D9 behavior but can produce worse-looking edges.",
            "inputs": "True=seamless, False=non-seamless (default)",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.seamlessCubes=", "", ";"),
        },
        "d3d9_texture_memory": {
            "label": "D3D9 Texture Memory (MB)",
            "description": "Virtual memory budget for locked D3D9 textures (in MB). 0=disable the limit. DOES NOT IMPACT ACTUAL MEMORY CONSUMPTION OR TEXTURE QUALITY. DO NOT CHANGE UNLESS YOU HAVE A VERY GOOD REASON.",
            "inputs": "value=megabytes (default 100), 0=no limit",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.textureMemory=", "", ";"),
        },
        "d3d9_device_loss_on_focus_loss": {
            "label": "Device Loss on Focus Loss",
            "description": "D3D9 requires the application to call Device::Reset after losing focus in fullscreen. Some games rely on observing D3DERR_DEVICELOST/D3DERR_NOTRESET; others don't handle it correctly.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.deviceLossOnFocusLoss=", "", ";"),
        },
        "d3d9_count_losable_resources": {
            "label": "Count Losable Resources",
            "description": "Reject Device::Reset if any losable resource is still alive (state blocks, additional swapchains, D3DPOOL_DEFAULT resources). Some games leak resources, leading to a hang; bypassing this works around that.",
            "inputs": "True=reject (default), False=allow",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.countLosableResources=", "", ";"),
        },
        "d3d9_extra_frontbuffer": {
            "label": "Extra Frontbuffer",
            "description": "Some games create a swapchain with only 1 buffer but expect GetFrontBufferData() to correctly return the last present's data. Adds a second buffer and copies to it every frame. Needed for modded Silent Hill 2 Enhanced Edition.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d9.extraFrontbuffer=", "", ";"),
        },
        "d3d11_max_feature_level": {
            "label": "D3D11 Max Feature Level",
            "description": "Override the maximum feature level that a D3D11 device can be created with. Setting this higher may allow some applications to run that would otherwise fail to create a D3D11 device.",
            "inputs": "12_1, 12_0, 11_1, 11_0, 10_1, 10_0, 9_3, 9_2, 9_1",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.maxFeatureLevel=", "", ";"),
        },
        "d3d11_max_tess_factor": {
            "label": "Max Tessellation Factor",
            "description": "Override the maximum allowed tessellation factor. Can improve performance in titles which overuse tessellation.",
            "inputs": "value=8-64, 0=app default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.maxTessFactor=", "", ";"),
        },
        "d3d11_constant_buffer_range_check": {
            "label": "Constant Buffer Range Check (Low-Latency)",
            "description": "Perform range check on dynamically indexed constant buffers in shaders. Workaround for a certain type of game bug but may introduce incorrect behaviour. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.constantBufferRangeCheck=", "", ";"),
        },
        "d3d11_dc_single_use_mode": {
            "label": "DC Single Use Mode (Low-Latency)",
            "description": "Assume single-use mode for command lists created on deferred contexts. May need to be off for some applications to avoid rendering issues, at a significant performance cost. Low-latency fork only.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.dcSingleUseMode=", "", ";"),
        },
        "d3d11_relaxed_barriers": {
            "label": "Relaxed Barriers",
            "description": "Relaxed pipeline barriers around UAV writes. Ignores write-after-write hazards in compute shaders and all UAV hazards in graphics shaders. May improve performance but can introduce rendering issues. Do not report bugs with this active.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.relaxedBarriers=", "", ";"),
        },
        "d3d11_relaxed_graphics_barriers": {
            "label": "Relaxed Graphics Barriers",
            "description": "Relaxed UAV pipeline barriers in graphics shaders only (not compute). Do not report bugs with this active.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.relaxedGraphicsBarriers=", "", ";"),
        },
        "d3d11_ignore_graphics_barriers": {
            "label": "Ignore Graphics Barriers (Low-Latency)",
            "description": "Ignore barriers around UAV writes from fragment shaders. May improve performance but can introduce rendering issues. Do not report bugs with this active. Low-latency fork only (upstream uses relaxedGraphicsBarriers).",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.ignoreGraphicsBarriers=", "", ";"),
        },
        "d3d11_sampler_anisotropy": {
            "label": "D3D11 Sampler Anisotropy",
            "description": "Override anisotropic filtering for all samplers. Positive values force AF for all samplers; 0 suppresses AF entirely; negative has no effect. Known to break passes that rely on bilinear filtering. Do not report bugs with this active.",
            "inputs": "value=0-16, 0=off, -1=app default",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.samplerAnisotropy=", "", ";"),
        },
        "d3d11_sampler_lod_bias": {
            "label": "D3D11 Sampler LOD Bias",
            "description": "Change the mipmap LOD bias for all samplers. Added to (not replacing) the app-provided bias. Positive reduces texture detail, negative may increase sharpness at the cost of shimmer.",
            "inputs": "value=-2.0 to 1.0",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.samplerLodBias=", "", ";"),
        },
        "d3d11_clamp_negative_lod_bias": {
            "label": "D3D11 Clamp Negative LOD Bias",
            "description": "Clamp any negative LOD bias to 0. Applied after samplerLodBias. May help with games that use a high negative LOD bias by default.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.clampNegativeLodBias=", "", ";"),
        },
        "d3d11_sample_rate_shading": {
            "label": "D3D11 Sample Rate Shading",
            "description": "Force per-sample rate shading when MSAA is active, rather than per-pixel shading. May improve visual clarity at a significant performance cost; may also introduce visual issues in some games.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.forceSampleRateShading=", "", ";"),
        },
        "d3d11_invariant_position": {
            "label": "D3D11 Invariant Position (Low-Latency)",
            "description": "Declare vertex positions as invariant to solve potential Z-fighting issues at a small performance cost. Low-latency fork only.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.invariantPosition=", "", ";"),
        },
        "d3d11_msaa": {
            "label": "D3D11 MSAA",
            "description": "MSAA support. Off forces the sample count of all textures to 1, performing needed fixups in resolve operations and shaders.",
            "inputs": "False=on, True=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.disableMsaa=", "", ";"),
        },
        "d3d11_zero_workgroup_memory": {
            "label": "Zero Workgroup Memory (Low-Latency)",
            "description": "Clear workgroup memory in compute shaders to zero. Some games don't do this and rely on undefined behaviour. Active may reduce performance. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.zeroWorkgroupMemory=", "", ";"),
        },
        "d3d11_compute_lds_barriers": {
            "label": "Compute LDS Barriers",
            "description": "Insertion of memory and control barriers after writes to group-shared memory in compute shaders. Workaround for games that don't properly synchronize access to groupshared variables. May hurt performance.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.forceComputeLdsBarriers=", "", ";"),
        },
        "d3d11_compute_uav_barriers": {
            "label": "Compute UAV Barriers",
            "description": "Insertion of full memory and control barriers after accessing any read-write UAV inside compute shaders. Workaround for games that don't synchronize access to coherent UAVs. Will likely hurt performance.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.forceComputeUavBarriers=", "", ";"),
        },
        "d3d11_max_implicit_discard_size": {
            "label": "Max Implicit Discard Size KB (Low-Latency)",
            "description": "Resource size limit for implicit discards, in kilobytes. For small staging resources mapped with MAP_WRITE, DXVK sometimes allocates new backing storage to avoid GPU sync. Too high may cause memory issues. -1 is off. Low-latency fork only.",
            "inputs": "value=KB (default 256), -1=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.maxImplicitDiscardSize=", "", ";"),
        },
        "d3d11_max_dynamic_image_buffer_size": {
            "label": "Max Dynamic Image Buffer Size KB (Low-Latency)",
            "description": "Resource size limit for buffer-mapped dynamic images, in kilobytes. Higher threshold may reduce memory/PCI-E bandwidth in some games but may increase GPU synchronizations. -1 is off. Low-latency fork only.",
            "inputs": "value=KB, -1=off (default)",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.maxDynamicImageBufferSize=", "", ";"),
        },
        "d3d11_cached_dynamic_resources": {
            "label": "D3D11 Cached Dynamic Resources",
            "description": "Allocate dynamic resources with the given bind flags in cached system memory rather than uncached memory or host-visible VRAM, to allow fast CPU readback. Only useful for buggy applications; may reduce GPU-bound performance.",
            "inputs": "v=vertex, i=index, c=constant, r=shader resources, a=all (e.g. 'vic')",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.cachedDynamicResources=", "", ";"),
        },
        "d3d11_direct_image_mapping": {
            "label": "Direct Image Mapping",
            "description": "Direct image mapping. Suppressing acts as workaround for bugs where the game ignores the implementation-defined row pitch for mapped dynamic images and expects tightly packed data, which can result in visual corruption.",
            "inputs": "False=on, True=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.disableDirectImageMapping=", "", ";"),
        },
        "d3d11_context_lock": {
            "label": "D3D11 Context Lock",
            "description": "D3D11 context lock via the ID3D10Multithread interface. Useful to debug race conditions.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.enableContextLock=", "", ";"),
        },
        "d3d11_driver_command_lists": {
            "label": "Driver Command Lists",
            "description": "Report support for driver command lists. Some games use this feature flag to decide whether to use deferred contexts. Disabling may help games that misbehave when detecting an AMD GPU (where command lists are not natively supported on Windows).",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.exposeDriverCommandLists=", "", ";"),
        },
        "d3d11_reproducible_command_stream": {
            "label": "D3D11 Reproducible Command Stream",
            "description": "Ensure the same D3D commands produce the same Vulkan commands between runs. Useful for comparative benchmarking. Can hurt performance and break some games that don't use queries correctly.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "d3d11.reproducibleCommandStream=", "", ";"),
        },
        "dxgi_hdr": {
            "label": "DXGI HDR",
            "description": "Expose HDR10 color space to the application by default. Shows the game that Windows 'HDR Mode' is active. Many broken games need this to consider exposing HDR output, as they check DXGIOutput's current ColorSpace instead of using CheckColorSpaceSupport. Defaults to the DXVK_HDR env var value.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.enableHDR=", "", ";"),
        },
        "dxgi_dummy_composition_swapchain": {
            "label": "DXGI Dummy Composition Swapchain",
            "description": "Expose support for dcomp swap chains with a dummy window. This is not a valid implementation of DirectComposition swapchains, but some games rely on this functionality being present while others require swap chain creation to fail.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.enableDummyCompositionSwapchain=", "", ";"),
        },
        "dxgi_ue4_workarounds": {
            "label": "UE4 HDR Workarounds",
            "description": "Unreal Engine 4 HDR workarounds for games that do not follow the standard -Win64-Shipping.exe naming scheme. May be needed to avoid crashes in D3D11 games on HDR systems due to statically linked AMDAGS.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.enableUe4Workarounds=", "", ";"),
        },
        "dxgi_defer_surface_creation": {
            "label": "DXGI Defer Surface Creation",
            "description": "Create the VkSurface on the first call to IDXGISwapChain::Present rather than at swap chain creation. Some games that start rendering with a different graphics API may need this, otherwise the window may stay black.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.deferSurfaceCreation=", "", ";"),
        },
        "dxgi_max_frame_latency": {
            "label": "DXGI Max Frame Latency",
            "description": "Enforce a stricter maximum frame latency. Overrides the application setting from IDXGIDevice::SetMaximumFrameLatency. Setting this to 0 has no effect.",
            "inputs": "value=0-16",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.maxFrameLatency=", "", ";"),
        },
        "dxgi_max_frame_rate": {
            "label": "DXGI Max Frame Rate",
            "description": "Frame rate limiter for DXGI. 0=default (cap to refresh rate under vsync if mode mismatches); n=limit to n fps; -n=limit to n fps only if running significantly faster for a short period (useful for app profiles); -1=always off (for games locked to low refresh rates).",
            "inputs": "n=limit to n fps, 0=default, -1=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.maxFrameRate=", "", ";"),
        },
        "dxgi_custom_device_id": {
            "label": "DXGI Custom Device ID",
            "description": "Override the PCI device ID reported to the application. Can cause games to adjust behaviour based on the selected value.",
            "inputs": "value=four-digit hex (e.g. 1002)",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.customDeviceId=", "", ";"),
        },
        "dxgi_custom_vendor_id": {
            "label": "DXGI Custom Vendor ID",
            "description": "Override the PCI vendor ID reported to the application. Common values: 1002=AMD, 10de=Nvidia, 8086=Intel.",
            "inputs": "value=four-digit hex (e.g. 1002)",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.customVendorId=", "", ";"),
        },
        "dxgi_custom_device_desc": {
            "label": "DXGI Custom Device Description",
            "description": "Override the reported device description string for DXGI.",
            "inputs": "value=any string",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.customDeviceDesc=", "", ";"),
        },
        "dxgi_hide_nvidia_gpu": {
            "label": "DXGI Hide Nvidia GPU",
            "description": "Report Nvidia GPUs as AMD GPUs. By default done for DXGI unless NVAPI is explicitly used through Proton, to work around crashes or low performance with Nvidia-specific code paths (especially Unreal Engine).",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.hideNvidiaGpu=", "", ";"),
        },
        "dxgi_hide_nvk_gpu": {
            "label": "DXGI Hide NVK GPU",
            "description": "Report Nvidia GPUs running on NVK (open source driver) as AMD GPUs.",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.hideNvkGpu=", "", ";"),
        },
        "dxgi_hide_amd_gpu": {
            "label": "DXGI Hide AMD GPU",
            "description": "Report AMD GPUs as Nvidia GPUs. Only done for games known to have issues with AMDAGS or other AMD-specific code paths.",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.hideAmdGpu=", "", ";"),
        },
        "dxgi_hide_intel_gpu": {
            "label": "DXGI Hide Intel GPU",
            "description": "Report Intel GPUs as AMD GPUs. Only done for games known to have issues with Intel-specific libraries such as XESS.",
            "inputs": "True=on (default), False=off, Auto=auto",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.hideIntelGpu=", "", ";"),
        },
        "dxgi_max_device_memory": {
            "label": "Max Device Memory (MB)",
            "description": "Override the maximum amount of device memory reported to the application. May fix texture streaming issues in games that do not support cards with large amounts of VRAM. Not a hard cap; applications may ignore it.",
            "inputs": "value=megabytes (0=no override)",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.maxDeviceMemory=", "", ";"),
        },
        "dxgi_max_shared_memory": {
            "label": "Max Shared Memory (MB)",
            "description": "Override the maximum amount of shared system memory reported to the application. Used alongside maxDeviceMemory for texture streaming workarounds.",
            "inputs": "value=megabytes (0=no override)",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.maxSharedMemory=", "", ";"),
        },
        "dxgi_emulate_uma": {
            "label": "Emulate UMA (Low-Latency)",
            "description": "Some games think we are on Intel given a lack of NVAPI or AGS/atiadlxx support. Reports device memory as shared memory plus a small 'carveout'. Low-latency fork only.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.emulateUMA=", "", ";"),
        },
        "dxgi_num_back_buffers": {
            "label": "DXGI Num Back Buffers (Low-Latency)",
            "description": "Override back buffer count for the Vulkan swap chain. Setting to 0 or less has no effect. Low-latency fork only.",
            "inputs": "value>=2, 0=no override",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.numBackBuffers=", "", ";"),
        },
        "dxgi_sync_interval": {
            "label": "DXGI Sync Interval (Vsync)",
            "description": "Override vsync sync interval. 0=vsync off entirely; positive n=vsync on and repeat the same image n times; negative=no effect (use app setting).",
            "inputs": "n=repeat n times, 0=off, -1=app default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.syncInterval=", "", ";"),
        },
        "dxgi_refresh_rate": {
            "label": "DXGI Refresh Rate",
            "description": "Only expose modes with the given refresh rate (Hz). Useful for titles that select the lowest supported refresh rate. Many titles break (physics, rendering, etc.) when forcing high refresh rates. Do not report issues with this option.",
            "inputs": "value=Hz (e.g. 60, 120), 0=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxgi.forceRefreshRate=", "", ";"),
        },
        "dxvk_allow_fse": {
            "label": "Allow Exclusive Fullscreen",
            "description": "Allow the Vulkan driver to opt-in to exclusive full-screen mode on Windows. Required for VRR or HDR in some cases, but breaks games that use additional GDI windows and will also break alt+tab. No effect on non-Windows platforms.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.allowFse=", "", ";"),
        },
        "dxvk_latency_sleep": {
            "label": "Latency Sleep / Reflex",
            "description": "Controls latency sleep and Nvidia Reflex support. Auto=only D3D11+Reflex games with VK_NV_low_latency2 and dxvk-nvapi in Proton. True=force built-in latency reduction based on internal timings (assumes input sampling happens after Present returns; won't work with async-rendering games or external/in-game limiters; may reduce performance or hurt frame pacing). False=suppress Reflex and built-in latency reduction.",
            "inputs": "True=force on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.latencySleep=", "", ";"),
        },
        "dxvk_latency_tolerance": {
            "label": "Latency Tolerance (µs)",
            "description": "Tolerance for the latency sleep heuristic in microseconds. Higher values increase latency but may improve frame pacing. No effect if NV_low_latency2 is used.",
            "inputs": "value=non-negative number (default 1000)",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.latencyTolerance=", "", ";"),
        },
        "dxvk_nv_low_latency2": {
            "label": "NV_low_latency2",
            "description": "VK_NV_low_latency2 usage. Suppressing makes Reflex unavailable; if dxvk.latencySleep=True, a custom algorithm is used instead. By default the extension is not used in 32-bit applications due to driver issues.",
            "inputs": "False=force on, True=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.disableNvLowLatency2=", "", ";"),
        },
        "dxvk_tear_free": {
            "label": "Tear Free Mode",
            "description": "Controls tearing behaviour. True=use mailbox present mode when vsync is off (eliminates tearing, may be unsupported on some systems). False=use relaxed FIFO present mode when vsync is on (tearing but less stutter at low FPS). Do not report issues with this option.",
            "inputs": "True=mailbox, False=relaxed fifo, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.tearFree=", "", ";"),
        },
        "dxvk_tiler_mode": {
            "label": "Tiler Mode",
            "description": "Controls tiler optimizations. Alters submission heuristics and activates some non-default behaviour. Only intended for performance testing and debugging.",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.tilerMode=", "", ";"),
        },
        "dxvk_zero_mapped_memory": {
            "label": "Zero Mapped Memory",
            "description": "Clear mapped memory to zero when suballocated memory is freed. Drastically increases CPU overhead. Only use as a last resort if a game does not properly initialize mapped buffers on its own.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.zeroMappedMemory=", "", ";"),
        },
        "dxvk_num_compiler_threads": {
            "label": "Number of Compiler Threads",
            "description": "Number of pipeline compiler threads. With graphics pipeline library active, these threads are used for shader compilation (some reserved for high-priority work).",
            "inputs": "value=explicit thread count, 0=all CPU cores",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.numCompilerThreads=", "", ";"),
        },
        "dxvk_dyasync": {
            "label": "Dyasync (Sarek, Inline)",
            "description": "Toggle Dynamic Asynchronous Pipeline Compilation (Dyasync) via dxvk.conf. On first sight a shader is compiled synchronously; every subsequent variant (new fixed-function state combo) compiles in the background while DXVK uses the closest already-compiled pipeline as a placeholder. Reduces stuttering compared to fully synchronous compilation while remaining safer than traditional async patches. Use in multiplayer at your own discretion. Only applicable to DXVK-Sarek.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableDyasync=", "", ";"),
        },
        "dxvk_num_dyasync_threads": {
            "label": "Num Dyasync Threads (Sarek)",
            "description": "Number of Dyasync compiler threads. Only applicable to DXVK-Sarek.",
            "inputs": "value=explicit thread count, 0=auto",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.numDyasyncThreads=", "", ";"),
        },
        "dxvk_raw_ssbo": {
            "label": "Raw SSBO",
            "description": "Use storage buffers to implement raw and structured buffer views. Active by default on hardware with a 4-byte storage buffer offset alignment (e.g. AMD). May improve performance but is not safe on hardware with higher alignment requirements.",
            "inputs": "True=force on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.useRawSsbo=", "", ";"),
        },
        "dxvk_shrink_nvidia_hvv_heap": {
            "label": "Shrink Nvidia HVV Heap (Low-Latency)",
            "description": "Controls Nvidia HVV behaviour. Suppresses the host-visible, device-local heap on Nvidia drivers. Used to work around NVIDIA driver bug 3114283 on affected drivers, as well as in specific games on newer drivers. Low-latency fork only.",
            "inputs": "True=on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.shrinkNvidiaHvvHeap=", "", ";"),
        },
        "dxvk_graphics_pipeline_library": {
            "label": "Graphics Pipeline Library",
            "description": "Control VK_EXT_graphics_pipeline_library usage. Changing will likely result in increased stutter or degraded performance. Auto=on if supported and compile optimized pipelines in background. True=on but don't compile optimized pipelines. False=always off.",
            "inputs": "True=no optimized, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableGraphicsPipelineLibrary=", "", ";"),
        },
        "dxvk_descriptor_heap": {
            "label": "Descriptor Heap",
            "description": "VK_EXT_descriptor_heap usage.",
            "inputs": "True=force on, False=off, Auto=known-good drivers",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableDescriptorHeap=", "", ";"),
        },
        "dxvk_descriptor_buffer": {
            "label": "Descriptor Buffer",
            "description": "VK_EXT_descriptor_buffer usage. If descriptor heap feature is active and supported, it takes precedence over descriptor buffers.",
            "inputs": "True=force on, False=off, Auto=known-good drivers",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableDescriptorBuffer=", "", ";"),
        },
        "dxvk_unified_image_layouts": {
            "label": "Unified Image Layouts",
            "description": "Control image layout path. Can suppress VK_KHR_unified_image_layouts usage on supporting systems, as well as opportunistic paths on devices that don't support it. Only useful for debugging.",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableUnifiedImageLayouts=", "", ";"),
        },
        "dxvk_implicit_resolves": {
            "label": "Implicit Resolves",
            "description": "Control implicit resolves. Some games sample multisampled images as regular textures (undefined behaviour in Vulkan, causes striped patterns on Nvidia). DXVK performs SAMPLE_ZERO resolves on demand as a workaround. Suppress for games that don't need it (they have runtime checks inside shaders).",
            "inputs": "True=on (default), False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableImplicitResolves=", "", ";"),
        },
        "dxvk_track_pipeline_lifetime": {
            "label": "Track Pipeline Lifetime",
            "description": "If active, pipeline libraries are freed aggressively to save memory and address space. No effect if graphics pipeline libraries are not supported or off.",
            "inputs": "True=always, False=never, Auto=32-bit apps only",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.trackPipelineLifetime=", "", ";"),
        },
        "dxvk_memory_defrag": {
            "label": "Memory Defragmentation",
            "description": "Control memory defragmentation. By default, DXVK defragments video memory if significant memory is wasted or budget is exceeded. Provided solely for debug purposes.",
            "inputs": "True=force on, False=off, Auto=default",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableMemoryDefrag=", "", ";"),
        },
        "dxvk_hud_conf": {
            "label": "DXVK HUD (Inline)",
            "description": "Set active HUD elements via dxvk.conf. Behaves like the DXVK_HUD environment variable if that is not set; otherwise ignored. Same syntax as DXVK_HUD.",
            "inputs": "value=comma-separated HUD elements",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.hud=", "", ";"),
        },
        "dxvk_lower_sin_cos": {
            "label": "Lower Sin/Cos",
            "description": "Force custom sine/cosine approximation. On some hardware this may be more accurate than native sin/cos but at a performance cost.",
            "inputs": "True=force on, False=off, Auto=poor-precision drivers only",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.lowerSinCos=", "", ";"),
        },
        "dxvk_debug_utils": {
            "label": "Debug Utils (Inline)",
            "description": "Debug utils for user annotations like BeginEvent()/EndEvent(). Alternative to DXVK_DEBUG=markers env var.",
            "inputs": "True=on, False=off",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.enableDebugUtils=", "", ";"),
        },
        "dxvk_hide_integrated_graphics": {
            "label": "Hide Integrated Graphics",
            "description": "Only has an effect when dedicated GPUs are present. Not recommended unless absolutely necessary; prefer DXVK_FILTER_DEVICE_NAME whenever possible.",
            "inputs": "True=hide iGPU, False=show (default)",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.hideIntegratedGraphics=", "", ";"),
        },
        "dxvk_max_memory_budget": {
            "label": "Max Memory Budget (MB)",
            "description": "Limit the amount of VRAM that DXVK actually uses. Debug option only — expect severe performance degradation when active.",
            "inputs": "value=VRAM budget in MB, 0=off (default)",
            "output": ("environment_variable", "DXVK_CONFIG", "dxvk.maxMemoryBudget=", "", ";"),
        },
        "dxvk_log_level": {
            "label": "Log Level",
            "description": "Control DXVK log verbosity.",
            "inputs": "none=none, error=error, warn=warn, info=info, debug=debug",
            "output": ("environment_variable", "DXVK_LOG_LEVEL", "", "", ""),
        },
        "dxvk_log_path": {
            "label": "Log Path",
            "description": "Write DXVK log files to the specified directory. Set to 'none' to suppress log file creation without omitting stderr logging.",
            "inputs": "value=directory path, none=suppress log files",
            "output": ("environment_variable", "DXVK_LOG_PATH", "", "", ""),
        },
        "dxvk_debug": {
            "label": "Debug Utils",
            "description": "VK_EXT_debug_utils. 'markers' translates Direct3D performance event markers (BeginEvent/EndEvent). 'validation' loads Vulkan validation (requires Vulkan SDK installed).",
            "inputs": "markers=performance markers, validation=vulkan validation",
            "output": ("environment_variable", "DXVK_DEBUG", "", "", ""),
        },
    }
