def get_gamescope_settings() -> dict:
    return {
        "_tab_metadata": (True,),
        "gamescope": {
            "label": "Gamescope",
            "description": "Gamescope compositing window manager.",
            "inputs": "value=on",
            "output": ("argument", "gamescope", "", "", ""),
        },
        "gamescope_wsi_layer": {
            "label": "Gamescope WSI Layer",
            "description": "Gamescope Vulkan WSI layer activation.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "ENABLE_GAMESCOPE_WSI", "", "", ""),
        },
        "vulkan_wsi_minimum_image_count": {
            "label": "Vulkan WSI Minimum Image Count",
            "description": "Minimum swapchain image count for Gamescope WSI.",
            "inputs": "value=1, 2=2, 3=3, 4=4, 5=5, 6=6",
            "output": ("environment_variable", "GAMESCOPE_WSI_MIN_IMAGE_COUNT", "", "", ""),
        },
        "vulkan_preferred_device": {
            "label": "Vulkan Preferred Device",
            "description": "Preferred Vulkan device by vendor:device ID.",
            "inputs": "e.g. 1002:7300=e.g. 1002:7300",
            "output": ("argument", "--prefer-vk-device ", "", "", ""),
        },
        "gamescope_output_width": {
            "label": "Gamescope Output Width",
            "description": "Output resolution width.",
            "inputs": "1280=1280, 1920=1920, 2560=2560, 3840=3840",
            "output": ("argument", "-W ", "", "", ""),
        },
        "gamescope_output_height": {
            "label": "Gamescope Output Height",
            "description": "Output resolution height.",
            "inputs": "720=720, 1080=1080, 1440=1440, 2160=2160",
            "output": ("argument", "-H ", "", "", ""),
        },
        "gamescope_game_width": {
            "label": "Gamescope Game Width",
            "description": "Game rendering width.",
            "inputs": "1280=1280, 1920=1920, 2560=2560",
            "output": ("argument", "-w ", "", "", ""),
        },
        "gamescope_game_height": {
            "label": "Gamescope Game Height",
            "description": "Game rendering height.",
            "inputs": "720=720, 1080=1080, 1440=1440",
            "output": ("argument", "-h ", "", "", ""),
        },
        "nested_refresh_rate": {
            "label": "Nested Refresh Rate",
            "description": "Refresh rate when running nested.",
            "inputs": "30=30, 60=60, 120=120, 144=144, 165=165, 240=240",
            "output": ("argument", "-r ", "", "", ""),
        },
        "nested_unfocused_refresh_rate": {
            "label": "Nested Unfocused Refresh Rate",
            "description": "Refresh rate when nested and unfocused.",
            "inputs": "15=15, 30=30, 60=60",
            "output": ("argument", "-o ", "", "", ""),
        },
        "framerate_limit": {
            "label": "FPS Limit",
            "description": "FPS cap applied by Gamescope.",
            "inputs": "0=unlimited, 30=30, 60=60, 120=120, 144=144",
            "output": ("argument", "--framerate-limit=", "", "", ""),
        },
        "maximum_scale_factor": {
            "label": "Maximum Scale Factor",
            "description": "Maximum upscale factor.",
            "inputs": "1=1, 2=2, 3=3, 4=4",
            "output": ("argument", "-m ", "", "", ""),
        },
        "force_orientation": {
            "label": "Force Orientation",
            "description": "Force a specific display orientation.",
            "inputs": "normal=normal, left=left, right=right, upsidedown=upsidedown",
            "output": ("argument", "--force-orientation=", "", "", ""),
        },
        "display_index": {
            "label": "Display Index",
            "description": "Target display index.",
            "inputs": "0=0, 1=1, 2=2",
            "output": ("argument", "--display-index=", "", "", ""),
        },
        "preferred_output_connectors": {
            "label": "Preferred Output Connectors",
            "description": "Preferred output connector name.",
            "inputs": "DP-1=DP-1, HDMI-A-1=HDMI-A-1",
            "output": ("argument", "-O ", "", "", ""),
        },
        "gamescope_fullscreen": {
            "label": "Gamescope Fullscreen",
            "description": "Run in fullscreen mode.",
            "inputs": "value=on",
            "output": ("argument", "-f", "", "", ""),
        },
        "gamescope_borderless": {
            "label": "Gamescope Borderless",
            "description": "Run in borderless window mode.",
            "inputs": "value=on",
            "output": ("argument", "-b", "", "", ""),
        },
        "force_windows_fullscreen": {
            "label": "Force Windows Fullscreen",
            "description": "Force Windows games to use fullscreen.",
            "inputs": "value=on",
            "output": ("argument", "--force-windows-fullscreen", "", "", ""),
        },
        "scaler_backend": {
            "label": "Scaler Backend",
            "description": "Scaling mode.",
            "inputs": "auto=auto, integer=integer, fit=fit, fill=fill, stretch=stretch",
            "output": ("argument", "--scaler=", "", "", ""),
        },
        "gamescope_upscale_filter": {
            "label": "Gamescope Upscale Filter",
            "description": "Upscaling filter method.",
            "inputs": "linear=linear, nearest=nearest, fsr=fsr, nis=nis, pixel=pixel",
            "output": ("argument", "--filter=", "", "", ""),
        },
        "upscaler_sharpness": {
            "label": "Upscaler Sharpness",
            "description": "Sharpness level for FSR and NIS upscalers.",
            "inputs": "0=0, 2=2, 5=5, 10=10, 15=15, 20=20",
            "output": ("argument", "--sharpness=", "", "", ""),
        },
        "grab_keyboard": {
            "label": "Grab Keyboard",
            "description": "Grab keyboard input exclusively.",
            "inputs": "value=on",
            "output": ("argument", "-g", "", "", ""),
        },
        "force_grab_cursor": {
            "label": "Force Grab Cursor",
            "description": "Force cursor grab inside the window.",
            "inputs": "value=on",
            "output": ("argument", "--force-grab-cursor", "", "", ""),
        },
        "mouse_sensitivity": {
            "label": "Mouse Sensitivity",
            "description": "Mouse sensitivity multiplier.",
            "inputs": "0.5=0.5, 1.0=1.0, 1.5=1.5, 2.0=2.0",
            "output": ("argument", "-s ", "", "", ""),
        },
        "default_touch_mode": {
            "label": "Default Touch Mode",
            "description": "Default touch input mode.",
            "inputs": "0=0, 1=1, 2=2, 3=3, 4=4",
            "output": ("argument", "--default-touch-mode=", "", "", ""),
        },
        "cursor_image_path": {
            "label": "Cursor Image Path",
            "description": "Custom cursor image path.",
            "inputs": "filesystem_path=filesystem_path",
            "output": ("argument", "--cursor=", "", "", ""),
        },
        "hide_cursor_delay": {
            "label": "Hide Cursor Delay",
            "description": "Milliseconds before cursor is hidden.",
            "inputs": "3000=3000, 5000=5000, 10000=10000",
            "output": ("argument", "-C ", "", "", ""),
        },
        "cursor_scale_height": {
            "label": "Cursor Scale Height",
            "description": "Reference height for cursor scaling.",
            "inputs": "720=720, 1080=1080, 1440=1440",
            "output": ("argument", "--cursor-scale-height=", "", "", ""),
        },
        "rendering_backend": {
            "label": "Rendering Backend",
            "description": "Compositor backend.",
            "inputs": "auto=auto, drm=drm, sdl=sdl, openvr=openvr, headless=headless, wayland=wayland",
            "output": ("argument", "--backend=", "", "", ""),
        },
        "expose_wayland": {
            "label": "Expose Wayland",
            "description": "Expose a Wayland socket for child apps.",
            "inputs": "value=on",
            "output": ("argument", "--expose-wayland", "", "", ""),
        },
        "xwayland_server_count": {
            "label": "XWayland Server Count",
            "description": "Number of XWayland servers to spawn.",
            "inputs": "1=1, 2=2, 3=3",
            "output": ("argument", "--xwayland-count=", "", "", ""),
        },
        "adaptive_sync": {
            "label": "Adaptive Sync",
            "description": "Adaptive sync (VRR) output.",
            "inputs": "value=on",
            "output": ("argument", "--adaptive-sync", "", "", ""),
        },
        "immediate_flips": {
            "label": "Immediate Flips",
            "description": "Allow immediate page flips.",
            "inputs": "value=on",
            "output": ("argument", "--immediate-flips", "", "", ""),
        },
        "generate_direct_rendering_manager_mode": {
            "label": "Generate Direct Rendering Manager Mode",
            "description": "DRM mode generation method.",
            "inputs": "cvt=cvt, fixed=fixed",
            "output": ("argument", "--generate-drm-mode=", "", "", ""),
        },
        "high_dynamic_range_output": {
            "label": "HDR Output",
            "description": "HDR output mode.",
            "inputs": "value=on",
            "output": ("argument", "--hdr-enabled", "", "", ""),
        },
        "standard_dynamic_range_gamut_wideness": {
            "label": "SDR Gamut Wideness",
            "description": "SDR gamut wideness factor.",
            "inputs": "0.0=0.0, 0.25=0.25, 0.5=0.5, 0.75=0.75, 1.0=1.0",
            "output": ("argument", "--sdr-gamut-wideness=", "", "", ""),
        },
        "high_dynamic_range_standard_dynamic_range_content_nits": {
            "label": "HDR SDR Content Nits",
            "description": "SDR content brightness in HDR mode.",
            "inputs": "200=200, 400=400, 600=600, 800=800",
            "output": ("argument", "--hdr-sdr-content-nits=", "", "", ""),
        },
        "high_dynamic_range_inverse_tone_mapping": {
            "label": "HDR ITM",
            "description": "Inverse tone mapping for HDR.",
            "inputs": "value=on",
            "output": ("argument", "--hdr-itm-enabled", "", "", ""),
        },
        "high_dynamic_range_inverse_tone_mapping_standard_dynamic_range_nits": {
            "label": "HDR ITM SDR Input Nits",
            "description": "SDR input nits for inverse tone mapping.",
            "inputs": "100=100, 200=200, 400=400, 600=600, 1000=1000",
            "output": ("argument", "--hdr-itm-sdr-nits=", "", "", ""),
        },
        "high_dynamic_range_inverse_tone_mapping_target_nits": {
            "label": "HDR ITM Target Nits",
            "description": "Target nits for inverse tone mapping output.",
            "inputs": "400=400, 1000=1000, 2000=2000, 4000=4000, 10000=10000",
            "output": ("argument", "--hdr-itm-target-nits=", "", "", ""),
        },
        "color_management": {
            "label": "Disable Color Management",
            "description": "Disables Gamescope's color management pipeline (tone mapping, gamut conversion, ICC profile handling). Colors are passed through untouched. Useful for debugging or when the application already performs its own color management.",
            "inputs": "value=on",
            "output": ("argument", "--disable-color-management", "", "", ""),
        },
        "steam_integration": {
            "label": "Steam Integration",
            "description": "Steam overlay and input integration.",
            "inputs": "value=on",
            "output": ("argument", "-e", "", "", ""),
        },
        "mangoapp_overlay": {
            "label": "MangoApp Overlay",
            "description": "MangoApp performance overlay.",
            "inputs": "value=on",
            "output": ("argument", "--mangoapp", "", "", ""),
        },
        "reshade_effect": {
            "label": "Reshade Effect",
            "description": "ReShade effect file to load.",
            "inputs": "CRT.fx=CRT.fx",
            "output": ("argument", "--reshade-effect=", "", "", ""),
        },
        "reshade_technique_index": {
            "label": "Reshade Technique Index",
            "description": "ReShade technique index to use.",
            "inputs": "0=0, 1=1, 2=2",
            "output": ("argument", "--reshade-technique-idx=", "", "", ""),
        },
        "mura_compensation_map": {
            "label": "Mura Compensation Map",
            "description": "Mura compensation image path.",
            "inputs": "filesystem_path=filesystem_path",
            "output": ("argument", "--mura-map=", "", "", ""),
        },
        "hardware_planes": {
            "label": "Disable Hardware Planes",
            "description": "Disables hardware overlay plane usage. Forces Gamescope to composite everything in the shader pipeline instead of letting the display controller scan out overlays directly. Useful for debugging plane-related issues; usually hurts power efficiency.",
            "inputs": "value=on",
            "output": ("argument", "--disable-layers", "", "", ""),
        },
        "realtime_scheduling": {
            "label": "Realtime Scheduling",
            "description": "Realtime process scheduling priority.",
            "inputs": "value=on",
            "output": ("argument", "--rt", "", "", ""),
        },
        "keep_alive": {
            "label": "Keep Alive",
            "description": "Keep Gamescope running after child exits.",
            "inputs": "value=on",
            "output": ("argument", "--keep-alive", "", "", ""),
        },
        "allow_deferred_backend": {
            "label": "Allow Deferred Backend",
            "description": "Allow deferred backend initialization.",
            "inputs": "value=on",
            "output": ("argument", "--allow-deferred-backend", "", "", ""),
        },
        "statistics_path": {
            "label": "Statistics Path",
            "description": "Path for Gamescope statistics output.",
            "inputs": "filesystem_path=filesystem_path",
            "output": ("argument", "-T ", "", "", ""),
        },
        "ready_file_descriptor": {
            "label": "Ready FD",
            "description": "File descriptor signaled when ready.",
            "inputs": "3=3, 4=4",
            "output": ("argument", "-R ", "", "", ""),
        },
        "virtual_connector_strategy": {
            "label": "Virtual Connector Strategy",
            "description": "Virtual connector management strategy.",
            "inputs": "single-application=single-application, steam-controlled=steam-controlled",
            "output": ("argument", "--virtual-connector-strategy=", "", "", ""),
        },
        "virtual_reality_overlay_key": {
            "label": "Virtual Reality Overlay Key",
            "description": "OpenVR overlay key.",
            "inputs": "string=string",
            "output": ("argument", "--vr-overlay-key=", "", "", ""),
        },
        "virtual_reality_application_overlay_key": {
            "label": "Virtual Reality Application Overlay Key",
            "description": "OpenVR application overlay key.",
            "inputs": "string=string",
            "output": ("argument", "--vr-app-overlay-key=", "", "", ""),
        },
        "virtual_reality_overlay_explicit_name": {
            "label": "Virtual Reality Overlay Explicit Name",
            "description": "Explicit name for the OpenVR overlay.",
            "inputs": "string=string",
            "output": ("argument", "--vr-overlay-explicit-name=", "", "", ""),
        },
        "virtual_reality_overlay_default_name": {
            "label": "Virtual Reality Overlay Default Name",
            "description": "Default name for the OpenVR overlay.",
            "inputs": "string=string",
            "output": ("argument", "--vr-overlay-default-name=", "", "", ""),
        },
        "virtual_reality_overlay_icon": {
            "label": "Virtual Reality Overlay Icon",
            "description": "Icon path for the OpenVR overlay.",
            "inputs": "filesystem_path=filesystem_path",
            "output": ("argument", "--vr-overlay-icon=", "", "", ""),
        },
        "virtual_reality_overlay_show_immediately": {
            "label": "Virtual Reality Overlay Show Immediately",
            "description": "Show the OpenVR overlay immediately on launch.",
            "inputs": "value=on",
            "output": ("argument", "--vr-overlay-show-immediately", "", "", ""),
        },
        "virtual_reality_overlay_control_bar": {
            "label": "Virtual Reality Overlay Control Bar",
            "description": "Show control bar on the OpenVR overlay.",
            "inputs": "value=on",
            "output": ("argument", "--vr-overlay-enable-control-bar", "", "", ""),
        },
        "virtual_reality_overlay_keyboard_button": {
            "label": "Virtual Reality Overlay Keyboard Button",
            "description": "Show keyboard button on the OpenVR overlay control bar.",
            "inputs": "value=on",
            "output": ("argument", "--vr-overlay-enable-control-bar-keyboard", "", "", ""),
        },
        "virtual_reality_overlay_close_button": {
            "label": "Virtual Reality Overlay Close Button",
            "description": "Show close button on the OpenVR overlay control bar.",
            "inputs": "value=on",
            "output": ("argument", "--vr-overlay-enable-control-bar-close", "", "", ""),
        },
        "virtual_reality_overlay_click_stabilization": {
            "label": "Virtual Reality Overlay Click Stabilization",
            "description": "Click stabilization for the OpenVR overlay.",
            "inputs": "value=on",
            "output": ("argument", "--vr-overlay-enable-click-stabilization", "", "", ""),
        },
        "virtual_reality_overlay_modal": {
            "label": "Virtual Reality Overlay Modal",
            "description": "Modal mode for the OpenVR overlay.",
            "inputs": "value=on",
            "output": ("argument", "--vr-overlay-modal", "", "", ""),
        },
        "virtual_reality_overlay_physical_width": {
            "label": "Virtual Reality Overlay Physical Width",
            "description": "Physical width of the OpenVR overlay in meters.",
            "inputs": "1.0=1.0, 1.5=1.5, 2.0=2.0, 2.5=2.5, 3.0=3.0",
            "output": ("argument", "--vr-overlay-physical-width=", "", "", ""),
        },
        "virtual_reality_overlay_physical_curvature": {
            "label": "Virtual Reality Overlay Physical Curvature",
            "description": "Curvature of the OpenVR overlay surface.",
            "inputs": "0.0=0.0, 0.1=0.1, 0.25=0.25, 0.5=0.5",
            "output": ("argument", "--vr-overlay-physical-curvature=", "", "", ""),
        },
        "virtual_reality_overlay_pre_curve_pitch": {
            "label": "Virtual Reality Overlay Pre Curve Pitch",
            "description": "Pre-curve pitch of the OpenVR overlay.",
            "inputs": "0.0=0.0, 0.1=0.1, 0.25=0.25",
            "output": ("argument", "--vr-overlay-physical-pre-curve-pitch=", "", "", ""),
        },
        "virtual_reality_trackpad_scroll_speed": {
            "label": "Virtual Reality Trackpad Scroll Speed",
            "description": "Trackpad scroll speed in VR mode.",
            "inputs": "2.0=2.0, 4.0=4.0, 8.0=8.0, 12.0=12.0, 16.0=16.0",
            "output": ("argument", "--vr-scrolls-speed=", "", "", ""),
        },
        "debug_hardware_planes": {
            "label": "Debug Hardware Planes",
            "description": "Debug hardware overlay plane usage.",
            "inputs": "value=on",
            "output": ("argument", "--debug-layers", "", "", ""),
        },
        "debug_focus": {
            "label": "Debug Focus",
            "description": "Debug window focus handling.",
            "inputs": "value=on",
            "output": ("argument", "--debug-focus", "", "", ""),
        },
        "synchronous_x11": {
            "label": "Synchronous X11",
            "description": "Synchronous X11 mode for debugging.",
            "inputs": "value=on",
            "output": ("argument", "--synchronous-x11", "", "", ""),
        },
        "debug_heads_up_display": {
            "label": "Debug HUD",
            "description": "Debug HUD overlay.",
            "inputs": "value=on",
            "output": ("argument", "--debug-hud", "", "", ""),
        },
        "debug_x11_events": {
            "label": "Debug X11 Events",
            "description": "Debug X11 event handling.",
            "inputs": "value=on",
            "output": ("argument", "--debug-events", "", "", ""),
        },
        "force_composition": {
            "label": "Force Composition",
            "description": "Force compositing even when unnecessary.",
            "inputs": "value=on",
            "output": ("argument", "--force-composition", "", "", ""),
        },
        "composite_debug_markers": {
            "label": "Composite Debug Markers",
            "description": "Debug markers in composite output.",
            "inputs": "value=on",
            "output": ("argument", "--composite-debug", "", "", ""),
        },
        "x_resource": {
            "label": "Disable X Resource Extension",
            "description": "Disables Gamescope's use of the X-Resource extension for GPU usage tracking. Only relevant for debugging tools that conflict with Gamescope's resource queries.",
            "inputs": "value=on",
            "output": ("argument", "--disable-xres", "", "", ""),
        },
        "high_dynamic_range_debug_force_support": {
            "label": "HDR Debug Force Support",
            "description": "Force HDR support reporting for debugging.",
            "inputs": "value=on",
            "output": ("argument", "--hdr-debug-force-support", "", "", ""),
        },
        "high_dynamic_range_debug_force_output": {
            "label": "HDR Debug Force Output",
            "description": "Force HDR output for debugging.",
            "inputs": "value=on",
            "output": ("argument", "--hdr-debug-force-output", "", "", ""),
        },
        "high_dynamic_range_debug_heatmap": {
            "label": "HDR Debug Heatmap",
            "description": "HDR heatmap debug overlay.",
            "inputs": "value=on",
            "output": ("argument", "--hdr-debug-heatmap", "", "", ""),
        },
    }
