def get_mangohud_settings() -> dict:
    return {
        "_tab_metadata": (True,),
        "mangohud_argument": {
            "label": "MangoHud Argument",
            "description": "MangoHud command prefix.",
            "inputs": "value=on",
            "output": ("argument", "mangohud", "", "", ""),
        },
        "mangohud_environment_variable": {
            "label": "MangoHud Environment Variable",
            "description": "MangoHud activation variable.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "MANGOHUD", "", "", ""),
        },
        "mangohud_suppression": {
            "label": "MangoHud Suppression",
            "description": "Suppress MangoHud even when active.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "DISABLE_MANGOHUD", "", "", ""),
        },
        "opengl_vertical_synchronization": {
            "label": "OpenGL VSync",
            "description": "VSync mode for OpenGL via MangoHud.",
            "inputs": "1=on, 0=off, -1=adaptive",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "gl_vsync=", "", ","),
        },
        "opengl_libraries_path": {
            "label": "OpenGL Libraries Path",
            "description": "Override path for MangoHud OpenGL libraries.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "MANGOHUD_OPENGL_LIBS", "", "", ""),
        },
        "vulkan_vertical_synchronization": {
            "label": "Vulkan VSync",
            "description": "VSync mode for Vulkan via MangoHud.",
            "inputs": "3=on, 1=off, 0=adaptive, 2=mailbox",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "vsync=", "", ","),
        },
        "vulkan_driver": {
            "label": "Vulkan Driver",
            "description": "Show Vulkan driver name in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "vulkan_driver", ","),
        },
        "configuration_file": {
            "label": "Configuration File",
            "description": "Override path for the MangoHud config file.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "MANGOHUD_CONFIGFILE", "", "", ""),
        },
        "presets_file": {
            "label": "Presets File",
            "description": "Override path for the MangoHud presets file.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "MANGOHUD_PRESETSFILE", "", "", ""),
        },
        "read_configuration": {
            "label": "Read Configuration File",
            "description": "Read the MangoHud configuration file.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "read_cfg", ","),
        },
        "anisotropic_filtering": {
            "label": "Aniso Filtering",
            "description": "Anisotropic filtering level via MangoHud.",
            "inputs": "0=0, 1=1, 2=2, 4=4, 8=8, 16=16",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "af=", "", ","),
        },
        "mipmap_level_of_detail_bias": {
            "label": "Mipmap LOD Bias",
            "description": "Mipmap LOD bias via MangoHud.",
            "inputs": "-16 to 16=-16 to 16",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "picmip=", "", ","),
        },
        "bicubic_filtering": {
            "label": "Bicubic Filtering",
            "description": "Bicubic texture filtering via MangoHud.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "bicubic", ","),
        },
        "trilinear_filtering": {
            "label": "Trilinear Filtering",
            "description": "Trilinear texture filtering via MangoHud.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "trilinear", ","),
        },
        "retro_filtering": {
            "label": "Retro Filtering",
            "description": "Retro texture filtering via MangoHud.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "retro", ","),
        },
        "frames_per_second_limit": {
            "label": "FPS Limit",
            "description": "FPS limiter via MangoHud.",
            "inputs": "0=unlimited, 30=30, 60=60, 144=144",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps_limit=", "", ","),
        },
        "frames_per_second_limit_method": {
            "label": "FPS Limit Method",
            "description": "FPS limiter timing method.",
            "inputs": "late=late, early=early",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps_limit_method=", "", ","),
        },
        "preset": {
            "label": "Preset",
            "description": "Overlay display preset.",
            "inputs": "0=no-overlay, 1=fps-only, 2=horizontal, 3=extended, 4=detailed",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "preset=", "", ","),
        },
        "full_overlay": {
            "label": "Full Overlay",
            "description": "Show all overlay elements.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "full", ","),
        },
        "frames_per_second_only": {
            "label": "FPS Only",
            "description": "Show only FPS in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "fps_only", ","),
        },
        "no_display": {
            "label": "No Display",
            "description": "Hide the overlay at startup.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "no_display", ","),
        },
        "horizontal_layout": {
            "label": "Horizontal Layout",
            "description": "Horizontal overlay layout.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "horizontal", ","),
        },
        "horizontal_stretch": {
            "label": "Horizontal Stretch",
            "description": "Stretch horizontal layout to full width.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "horizontal_stretch", ","),
        },
        "compact": {
            "label": "Compact Overlay",
            "description": "Compact overlay layout.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "hud_compact", ","),
        },
        "no_margin": {
            "label": "No Margin",
            "description": "Remove overlay margin.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "hud_no_margin", ","),
        },
        "position": {
            "label": "Position",
            "description": "Overlay screen position.",
            "inputs": "top-left=top-left, top-right=top-right, top-center=top-center, middle-left=middle-left, middle-right=middle-right, bottom-left=bottom-left, bottom-right=bottom-right, bottom-center=bottom-center",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "position=", "", ","),
        },
        "width": {
            "label": "Width",
            "description": "Overlay width in pixels.",
            "inputs": "number=number",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "width=", "", ","),
        },
        "height": {
            "label": "Height",
            "description": "Overlay height in pixels.",
            "inputs": "number=number",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "height=", "", ","),
        },
        "offset_horizontal": {
            "label": "Horizontal Offset",
            "description": "Horizontal offset from the overlay position.",
            "inputs": "number=number",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "offset_x=", "", ","),
        },
        "offset_vertical": {
            "label": "Vertical Offset",
            "description": "Vertical offset from the overlay position.",
            "inputs": "number=number",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "offset_y=", "", ","),
        },
        "table_columns": {
            "label": "Table Columns",
            "description": "Number of overlay table columns.",
            "inputs": "1=1, 2=2, 3=3, 4=4, 5=5, 6=6",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "table_columns=", "", ","),
        },
        "cell_padding_vertical": {
            "label": "Vertical Cell Padding",
            "description": "Vertical padding between overlay rows.",
            "inputs": "number=number",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "cellpadding_y=", "", ","),
        },
        "round_corners": {
            "label": "Round Corners",
            "description": "Overlay corner rounding radius.",
            "inputs": "0=0, 5=5, 10=10, 15=15, 20=20",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "round_corners=", "", ","),
        },
        "frames_per_second_display": {
            "label": "FPS Display",
            "description": "FPS counter in the overlay.",
            "inputs": "0=off",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps=", "", ","),
        },
        "frames_per_second_sampling_period": {
            "label": "FPS Sampling Period",
            "description": "FPS averaging period in milliseconds.",
            "inputs": "100=100, 200=200, 500=500, 1000=1000, 2000=2000",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps_sampling_period=", "", ","),
        },
        "frames_per_second_color_change": {
            "label": "FPS Color Change",
            "description": "FPS color changes based on thresholds.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "fps_color_change", ","),
        },
        "frames_per_second_colors": {
            "label": "FPS Colors",
            "description": "FPS threshold colors as hex values.",
            "inputs": "hex=hex colors",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps_color=", "", ","),
        },
        "frames_per_second_color_breakpoints": {
            "label": "FPS Color Breakpoints",
            "description": "FPS values at which colors change.",
            "inputs": "30=30, 60=60",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps_value=", "", ","),
        },
        "frames_per_second_metrics": {
            "label": "FPS Metrics",
            "description": "Additional FPS percentile metrics.",
            "inputs": "avg=avg, 0.1=0.1, 0.01=0.01, 0.001=0.001",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps_metrics=", "", ","),
        },
        "frames_per_second_text": {
            "label": "FPS Text",
            "description": "Custom label text for the FPS counter.",
            "inputs": "text=text",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fps_text=", "", ","),
        },
        "show_frames_per_second_limit": {
            "label": "Show FPS Limit",
            "description": "Show the active FPS limit in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "show_fps_limit", ","),
        },
        "benchmark_percentiles": {
            "label": "Benchmark Percentiles",
            "description": "Benchmark percentile values to display.",
            "inputs": "97=97, AVG=AVG, 1=1, 0.1=0.1",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "benchmark_percentiles=", "", ","),
        },
        "frame_count": {
            "label": "Frame Count",
            "description": "Total frame counter in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "frame_count", ","),
        },
        "frametime": {
            "label": "Frametime",
            "description": "Frametime value in the overlay.",
            "inputs": "0=off",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "frametime=", "", ","),
        },
        "frame_timing": {
            "label": "Frame Timing Graph",
            "description": "Frametime graph in the overlay.",
            "inputs": "0=off",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "frame_timing=", "", ","),
        },
        "frame_timing_detailed": {
            "label": "Detailed Frame Timing",
            "description": "Detailed frametime breakdown graph.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "frame_timing_detailed", ","),
        },
        "dynamic_frame_timing": {
            "label": "Dynamic Frame Timing",
            "description": "Dynamic frametime graph scaling.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "dynamic_frame_timing", ","),
        },
        "histogram": {
            "label": "Histogram",
            "description": "FPS histogram graph.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "histogram", ","),
        },
        "cpu_statistics": {
            "label": "CPU Statistics",
            "description": "CPU load statistics in the overlay.",
            "inputs": "0=off",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "cpu_stats=", "", ","),
        },
        "cpu_temperature": {
            "label": "CPU Temperature",
            "description": "Show CPU temperature in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "cpu_temp", ","),
        },
        "cpu_power": {
            "label": "CPU Power",
            "description": "Show CPU power draw in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "cpu_power", ","),
        },
        "cpu_megahertz": {
            "label": "CPU MHz",
            "description": "Show CPU clock speed in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "cpu_mhz", ","),
        },
        "cpu_text": {
            "label": "CPU Text Override",
            "description": "Custom label text for the CPU section.",
            "inputs": "text=text",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "cpu_text=", "", ","),
        },
        "cpu_load_color_change": {
            "label": "CPU Load Color Change",
            "description": "CPU load color changes based on thresholds.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "cpu_load_change", ","),
        },
        "cpu_load_thresholds": {
            "label": "CPU Load Thresholds",
            "description": "CPU load percentage thresholds for color change.",
            "inputs": "50=50, 90=90",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "cpu_load_value=", "", ","),
        },
        "cpu_load_colors": {
            "label": "CPU Load Colors",
            "description": "CPU load threshold colors as hex values.",
            "inputs": "0000FF=0000FF, 00FFFF=00FFFF, FF00FF=FF00FF",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "cpu_load_color=", "", ","),
        },
        "cpu_efficiency": {
            "label": "CPU Efficiency",
            "description": "Show CPU efficiency metric in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "cpu_efficiency", ","),
        },
        "cpu_custom_temperature_sensor": {
            "label": "CPU Custom Temperature Sensor",
            "description": "Custom hwmon path for CPU temperature.",
            "inputs": "filesystem=filesystem path",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "cpu_custom_temp_sensor=", "", ","),
        },
        "core_load": {
            "label": "Core Load",
            "description": "Per-core CPU load in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "core_load", ","),
        },
        "core_load_color_change": {
            "label": "Core Load Color Change",
            "description": "Per-core load color changes based on thresholds.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "core_load_change", ","),
        },
        "core_load_bars": {
            "label": "Core Load Bars",
            "description": "Per-core load bar graph.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "core_bars", ","),
        },
        "core_type": {
            "label": "Core Type",
            "description": "Show CPU core type labels.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "core_type", ","),
        },
        "gpu_statistics": {
            "label": "GPU Statistics",
            "description": "GPU load statistics in the overlay.",
            "inputs": "0=off",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "gpu_stats=", "", ","),
        },
        "gpu_temperature": {
            "label": "GPU Temperature",
            "description": "Show GPU temperature in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_temp", ","),
        },
        "gpu_junction_temperature": {
            "label": "GPU Junction Temperature",
            "description": "Show GPU junction temperature in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_junction_temp", ","),
        },
        "gpu_memory_temperature": {
            "label": "GPU Memory Temperature",
            "description": "Show GPU memory temperature in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_mem_temp", ","),
        },
        "gpu_power": {
            "label": "GPU Power",
            "description": "Show GPU power draw in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_power", ","),
        },
        "gpu_core_clock": {
            "label": "GPU Core Clock",
            "description": "Show GPU core clock in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_core_clock", ","),
        },
        "gpu_memory_clock": {
            "label": "GPU Memory Clock",
            "description": "Show GPU memory clock in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_mem_clock", ","),
        },
        "gpu_fan": {
            "label": "GPU Fan",
            "description": "Show GPU fan speed in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_fan", ","),
        },
        "gpu_voltage": {
            "label": "GPU Voltage",
            "description": "Show GPU voltage in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_voltage", ","),
        },
        "gpu_name": {
            "label": "GPU Name",
            "description": "Show GPU name in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_name", ","),
        },
        "gpu_text": {
            "label": "GPU Text Override",
            "description": "Custom label text for the GPU section.",
            "inputs": "text=text",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "gpu_text=", "", ","),
        },
        "gpu_load_color_change": {
            "label": "GPU Load Color Change",
            "description": "GPU load color changes based on thresholds.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_load_change", ","),
        },
        "gpu_load_thresholds": {
            "label": "GPU Load Thresholds",
            "description": "GPU load percentage thresholds for color change.",
            "inputs": "50=50, 90=90",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "gpu_load_value=", "", ","),
        },
        "gpu_load_colors": {
            "label": "GPU Load Colors",
            "description": "GPU load threshold colors as hex values.",
            "inputs": "0000FF=0000FF, 00FFFF=00FFFF, FF00FF=FF00FF",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "gpu_load_color=", "", ","),
        },
        "gpu_efficiency": {
            "label": "GPU Efficiency",
            "description": "Show GPU efficiency metric in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_efficiency", ","),
        },
        "gpu_power_limit": {
            "label": "GPU Power Limit",
            "description": "Show GPU power limit in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gpu_power_limit", ","),
        },
        "gpu_list": {
            "label": "GPU List",
            "description": "GPU indices to monitor.",
            "inputs": "0=0, 1=1",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "gpu_list=", "", ","),
        },
        "pci_device": {
            "label": "PCI Device",
            "description": "PCI device address to monitor.",
            "inputs": "device=device address",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "pci_dev=", "", ","),
        },
        "throttling_status": {
            "label": "Throttling Status",
            "description": "Show GPU throttling status in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "throttling_status", ","),
        },
        "throttling_status_graph": {
            "label": "Throttling Status Graph",
            "description": "GPU throttling status graph.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "throttling_status_graph", ","),
        },
        "flip_efficiency": {
            "label": "Flip Efficiency",
            "description": "Show flip efficiency metric in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "flip_efficiency", ","),
        },
        "ram_usage": {
            "label": "RAM Usage",
            "description": "Show system RAM usage in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "ram", ","),
        },
        "vram_usage": {
            "label": "VRAM Usage",
            "description": "Show GPU VRAM usage in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "vram", ","),
        },
        "swap_usage": {
            "label": "Swap Usage",
            "description": "Show swap memory usage in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "swap", ","),
        },
        "ram_temperature": {
            "label": "RAM Temperature",
            "description": "Show RAM temperature in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "ram_temp", ","),
        },
        "process_memory_resident": {
            "label": "Process Memory Resident",
            "description": "Show process resident memory usage.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "procmem", ","),
        },
        "process_memory_shared": {
            "label": "Process Memory Shared",
            "description": "Show process shared memory usage.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "procmem_shared", ","),
        },
        "process_memory_virtual": {
            "label": "Process Memory Virtual",
            "description": "Show process virtual memory usage.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "procmem_virt", ","),
        },
        "process_vram": {
            "label": "Process VRAM",
            "description": "Show process VRAM usage.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "proc_vram", ","),
        },
        "input_output_read": {
            "label": "IO Read",
            "description": "Show disk read throughput in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "io_read", ","),
        },
        "input_output_write": {
            "label": "IO Write",
            "description": "Show disk write throughput in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "io_write", ","),
        },
        "network": {
            "label": "Network",
            "description": "Show network throughput in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "network", ","),
        },
        "battery": {
            "label": "Battery",
            "description": "Show battery level in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "battery", ","),
        },
        "battery_icon": {
            "label": "Battery Icon",
            "description": "Show battery icon in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "battery_icon", ","),
        },
        "battery_wattage": {
            "label": "Battery Wattage",
            "description": "Show battery wattage in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "battery_watt", ","),
        },
        "battery_time_remaining": {
            "label": "Battery Time Remaining",
            "description": "Show battery time remaining in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "battery_time", ","),
        },
        "device_battery": {
            "label": "Device Battery",
            "description": "Show external device battery levels.",
            "inputs": "gamepad=gamepad, mouse=mouse",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "device_battery=", "", ","),
        },
        "device_battery_icon": {
            "label": "Device Battery Icon",
            "description": "Show external device battery icons.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "device_battery_icon", ","),
        },
        "engine_version": {
            "label": "Engine Version",
            "description": "Show game engine version in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "engine_version", ","),
        },
        "engine_short_names": {
            "label": "Engine Short Names",
            "description": "Use short engine name labels.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "engine_short_names", ","),
        },
        "wine_version": {
            "label": "Wine Proton Version",
            "description": "Show Wine or Proton version in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "wine", ","),
        },
        "wine_synchronization_method": {
            "label": "Wine Synchronization Method",
            "description": "Show Wine sync method in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "winesync", ","),
        },
        "present_mode": {
            "label": "Present Mode",
            "description": "Show Vulkan present mode in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "present_mode", ","),
        },
        "fsr_status": {
            "label": "FSR Status",
            "description": "Show FSR status in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "fsr", ","),
        },
        "hide_fsr_sharpness": {
            "label": "Hide FSR Sharpness",
            "description": "Hide FSR sharpness value from the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "hide_fsr_sharpness", ","),
        },
        "high_dynamic_range_status": {
            "label": "HDR Status",
            "description": "Show HDR status in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "hdr", ","),
        },
        "refresh_rate": {
            "label": "Refresh Rate",
            "description": "Show display refresh rate in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "refresh_rate", ","),
        },
        "debug_graph": {
            "label": "Debug Graph",
            "description": "Debug timing graph in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "debug", ","),
        },
        "steam_deck_fan": {
            "label": "Steam Deck Fan",
            "description": "Show Steam Deck fan speed in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "fan", ","),
        },
        "resolution": {
            "label": "Resolution",
            "description": "Show render resolution in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "resolution", ","),
        },
        "display_server": {
            "label": "Display Server",
            "description": "Show display server type in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "display_server", ","),
        },
        "architecture": {
            "label": "Architecture",
            "description": "Show CPU architecture in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "arch", ","),
        },
        "executable_name": {
            "label": "Executable Name",
            "description": "Show process executable name in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "exec_name", ","),
        },
        "time": {
            "label": "Time",
            "description": "Show current time in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "time", ","),
        },
        "time_format": {
            "label": "Time Format",
            "description": "Time format string for the overlay clock.",
            "inputs": "%T=%T, %H:%M=%H:%M, %I:%M %p=%I:%M %p",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "time_format=", "", ","),
        },
        "time_no_label": {
            "label": "Time No Label",
            "description": "Show time without a label prefix.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "time_no_label", ","),
        },
        "gamemode": {
            "label": "GameMode",
            "description": "Show GameMode status in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "gamemode", ","),
        },
        "vkbasalt": {
            "label": "vkBasalt",
            "description": "Show vkBasalt status in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "vkbasalt", ","),
        },
        "temperature_in_fahrenheit": {
            "label": "Temperature in Fahrenheit",
            "description": "Display temperatures in Fahrenheit.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "temp_fahrenheit", ","),
        },
        "show_version": {
            "label": "Show Version",
            "description": "Show MangoHud version in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "version", ","),
        },
        "custom_text": {
            "label": "Custom Text",
            "description": "Custom text line in the overlay.",
            "inputs": "text=text",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "custom_text=", "", ","),
        },
        "custom_text_center": {
            "label": "Custom Text Center",
            "description": "Centered custom text line in the overlay.",
            "inputs": "text=text",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "custom_text_center=", "", ","),
        },
        "execute": {
            "label": "Execute Command",
            "description": "Shell command whose output is shown in the overlay.",
            "inputs": "command=command",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "exec=", "", ","),
        },
        "media_player": {
            "label": "Media Player",
            "description": "Show media player info in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "media_player", ","),
        },
        "media_player_name": {
            "label": "Media Player Name",
            "description": "MPRIS player name to query.",
            "inputs": "player=player name",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "media_player_name=", "", ","),
        },
        "media_player_format": {
            "label": "Media Player Format",
            "description": "Format string for media player info.",
            "inputs": "{title};{artist};{album}={title};{artist};{album}",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "media_player_format=", "", ","),
        },
        "font_size": {
            "label": "Font Size",
            "description": "Primary overlay font size in points.",
            "inputs": "12=12, 14=14, 16=16, 18=18, 20=20, 24=24, 32=32, 48=48",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_size=", "", ","),
        },
        "font_size_secondary": {
            "label": "Font Size Secondary",
            "description": "Secondary overlay font size in points.",
            "inputs": "10=10, 11=11, 12=12, 14=14, 16=16, 18=18, 24=24",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_size_secondary=", "", ","),
        },
        "font_size_text": {
            "label": "Font Size Text",
            "description": "Text element font size in points.",
            "inputs": "12=12, 14=14, 16=16, 18=18, 20=20, 24=24, 32=32",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_size_text=", "", ","),
        },
        "font_scale": {
            "label": "Font Scale",
            "description": "Global font scale multiplier.",
            "inputs": "0.5=0.5, 0.75=0.75, 1.0=1.0, 1.25=1.25, 1.5=1.5, 2.0=2.0",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_scale=", "", ","),
        },
        "font_scale_media_player": {
            "label": "Font Scale Media Player",
            "description": "Font scale multiplier for media player text.",
            "inputs": "0.5=0.5, 0.75=0.75, 1.0=1.0, 1.25=1.25, 1.5=1.5",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_scale_media_player=", "", ","),
        },
        "font_file": {
            "label": "Font File",
            "description": "Custom font file path for the overlay.",
            "inputs": "filesystem=filesystem path",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_file=", "", ","),
        },
        "font_file_text": {
            "label": "Font File Text",
            "description": "Custom font file path for text elements.",
            "inputs": "filesystem=filesystem path",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_file_text=", "", ","),
        },
        "font_glyph_ranges": {
            "label": "Font Glyph Ranges",
            "description": "Additional glyph ranges to load for the font.",
            "inputs": "korean=korean, chinese=chinese, chinese_simplified=chinese_simplified, japanese=japanese, cyrillic=cyrillic, thai=thai, vietnamese=vietnamese, latin_ext_a=latin_ext_a, latin_ext_b=latin_ext_b",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "font_glyph_ranges=", "", ","),
        },
        "no_small_font": {
            "label": "No Small Font",
            "description": "Use the primary font size for all text.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "no_small_font", ","),
        },
        "text_alpha": {
            "label": "Text Alpha",
            "description": "Overlay text opacity.",
            "inputs": "0.0 to 1.0=0.0 to 1.0",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "alpha=", "", ","),
        },
        "background_alpha": {
            "label": "Background Alpha",
            "description": "Overlay background opacity.",
            "inputs": "0.0 to 1.0=0.0 to 1.0",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "background_alpha=", "", ","),
        },
        "gpu_color": {
            "label": "GPU Color",
            "description": "GPU section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "gpu_color=", "", ","),
        },
        "cpu_color": {
            "label": "CPU Color",
            "description": "CPU section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "cpu_color=", "", ","),
        },
        "vram_color": {
            "label": "VRAM Color",
            "description": "VRAM section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "vram_color=", "", ","),
        },
        "ram_color": {
            "label": "RAM Color",
            "description": "RAM section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "ram_color=", "", ","),
        },
        "input_output_color": {
            "label": "IO Color",
            "description": "I/O section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "io_color=", "", ","),
        },
        "engine_color": {
            "label": "Engine Color",
            "description": "Engine section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "engine_color=", "", ","),
        },
        "frametime_color": {
            "label": "Frametime Color",
            "description": "Frametime section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "frametime_color=", "", ","),
        },
        "background_color": {
            "label": "Background Color",
            "description": "Overlay background color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "background_color=", "", ","),
        },
        "text_color": {
            "label": "Text Color",
            "description": "General overlay text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "text_color=", "", ","),
        },
        "media_player_color": {
            "label": "Media Player Color",
            "description": "Media player section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "media_player_color=", "", ","),
        },
        "network_color": {
            "label": "Network Color",
            "description": "Network section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "network_color=", "", ","),
        },
        "wine_color": {
            "label": "Wine Color",
            "description": "Wine section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "wine_color=", "", ","),
        },
        "battery_color": {
            "label": "Battery Color",
            "description": "Battery section text color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "battery_color=", "", ","),
        },
        "horizontal_separator_color": {
            "label": "Horizontal Separator Color",
            "description": "Horizontal separator line color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "horizontal_separator_color=", "", ","),
        },
        "text_outline": {
            "label": "Text Outline",
            "description": "Text outline rendering.",
            "inputs": "0=off",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "text_outline=", "", ","),
        },
        "text_outline_color": {
            "label": "Text Outline Color",
            "description": "Text outline color.",
            "inputs": "hex=hex color",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "text_outline_color=", "", ","),
        },
        "text_outline_thickness": {
            "label": "Text Outline Thickness",
            "description": "Text outline thickness in pixels.",
            "inputs": "0.5=0.5, 1.0=1.0, 1.5=1.5, 2.0=2.0, 2.5=2.5, 3.0=3.0",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "text_outline_thickness=", "", ","),
        },
        "autostart_log": {
            "label": "Autostart Log",
            "description": "Seconds to wait before starting the log automatically.",
            "inputs": "0=0, 5=5, 10=10, 30=30, 60=60",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "autostart_log=", "", ","),
        },
        "log_duration": {
            "label": "Log Duration",
            "description": "Log recording duration in seconds.",
            "inputs": "10=10, 30=30, 60=60, 120=120, 300=300",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "log_duration=", "", ","),
        },
        "log_interval": {
            "label": "Log Interval",
            "description": "Log sampling interval in milliseconds.",
            "inputs": "0=0, 100=100, 250=250, 500=500, 1000=1000",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "log_interval=", "", ","),
        },
        "log_versioning": {
            "label": "Log Versioning",
            "description": "Append version suffix to log filenames.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "log_versioning", ","),
        },
        "output_folder": {
            "label": "Output Folder",
            "description": "Directory for log output files.",
            "inputs": "filesystem=filesystem path",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "output_folder=", "", ","),
        },
        "output_file": {
            "label": "Output File",
            "description": "Filename for log output.",
            "inputs": "filesystem=filesystem path",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "output_file=", "", ","),
        },
        "permit_upload": {
            "label": "Permit Upload",
            "description": "Allow log upload to flightlessmango.com.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "permit_upload", ","),
        },
        "upload_logs": {
            "label": "Auto Upload Logs",
            "description": "Automatically upload logs after recording.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "upload_logs", ","),
        },
        "fcat": {
            "label": "FCAT",
            "description": "FCAT overlay for frame capture analysis.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "fcat", ","),
        },
        "fcat_overlay_width": {
            "label": "FCAT Overlay Width",
            "description": "FCAT overlay bar width in pixels.",
            "inputs": "12=12, 24=24, 48=48",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fcat_overlay_width=", "", ","),
        },
        "fcat_screen_edge": {
            "label": "FCAT Screen Edge",
            "description": "Screen edge for the FCAT overlay bar.",
            "inputs": "1=1, 2=2, 3=3, 4=4",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "fcat_screen_edge=", "", ","),
        },
        "toggle_overlay": {
            "label": "Toggle Overlay Keybind",
            "description": "Keybind to toggle the overlay visibility.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "toggle_hud=", "", ","),
        },
        "toggle_logging": {
            "label": "Toggle Logging Keybind",
            "description": "Keybind to start and stop logging.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "toggle_logging=", "", ","),
        },
        "toggle_frames_per_second_limit": {
            "label": "Toggle FPS Limit Keybind",
            "description": "Keybind to cycle FPS limit presets.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "toggle_fps_limit=", "", ","),
        },
        "toggle_preset": {
            "label": "Toggle Preset Keybind",
            "description": "Keybind to cycle overlay presets.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "toggle_preset=", "", ","),
        },
        "toggle_overlay_position": {
            "label": "Toggle Overlay Position Keybind",
            "description": "Keybind to cycle overlay screen positions.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "toggle_hud_position=", "", ","),
        },
        "reload_configuration": {
            "label": "Reload Configuration Keybind",
            "description": "Keybind to reload the MangoHud config file.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "reload_cfg=", "", ","),
        },
        "reset_frames_per_second_metrics": {
            "label": "Reset FPS Metrics Keybind",
            "description": "Keybind to reset FPS metric accumulators.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "reset_fps_metrics=", "", ","),
        },
        "upload_log": {
            "label": "Upload Log Keybind",
            "description": "Keybind to upload the current log.",
            "inputs": "keybind=keybind",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "upload_log=", "", ","),
        },
        "control_socket": {
            "label": "Control Socket",
            "description": "Unix socket path for MangoHud IPC control.",
            "inputs": "socket=socket path",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "control=", "", ","),
        },
        "blacklist": {
            "label": "Blacklist",
            "description": "Comma-separated executable names to suppress MangoHud.",
            "inputs": "executable=executable name",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "blacklist=", "", ","),
        },
        "fex_statistics": {
            "label": "FEX Statistics",
            "description": "Show FEX emulation statistics in the overlay.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "fex_stats", ","),
        },
        "ftrace": {
            "label": "ftrace",
            "description": "ftrace-based CPU event tracing.",
            "inputs": "value=on",
            "output": ("environment_variable", "MANGOHUD_CONFIG", "", "ftrace", ","),
        },
    }
