def get_proton_settings() -> dict:
    return {
        "_tab_metadata": (True,),
        "proton_use_wined3d": {
            "label": "Use wined3d",
            "description": "Use OpenGL-based wined3d instead of Vulkan-based DXVK for d3d11, d3d10, and d3d9.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_USE_WINED3D", "", "", ""),
        },
        "proton_old_gl_string": {
            "label": "Old GL String",
            "description": "Set some driver overrides to limit the length of the GL extension string, for old games that crash on very long extension strings.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_OLD_GL_STRING", "", "", ""),
        },
        "proton_dxvk_d3d8": {
            "label": "DXVK D3D8",
            "description": "Use DXVK's d3d8.dll.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_DXVK_D3D8", "", "", ""),
        },
        "proton_d7vk_ddraw": {
            "label": "D7VK DDraw",
            "description": "Use ddraw.dll from the D7VK project for DirectX 7-or-lower games.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_D7VK_DDRAW", "", "", ""),
        },
        "wine_disable_vulkan_opwr": {
            "label": "Disable Vulkan OPWR",
            "description": "Enable hack to disable Vulkan other process window rendering which sometimes causes issues on Wayland due to blit being one frame behind.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "WINE_DISABLE_VULKAN_OPWR", "", "", ""),
        },
        "proton_vkreflex": {
            "label": "Vulkan Reflex",
            "description": "Enables DXVK-NVAPI's Vulkan Reflex layer to support Reflex in Vulkan games such as Portal RTX, Path of Exile 1 and 2, Doom TDA, etc.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_VKREFLEX", "", "", ""),
        },
        "proton_dxvk_sarek": {
            "label": "DXVK Sarek",
            "description": "Use the dxvk-sarek fork as DXVK replacement for older GPUs that don't properly support Vulkan 1.3 (supported Vulkan 1.1.x to 1.2.x).",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_DXVK_SAREK", "", "", ""),
        },
        "proton_dxvk_lowlatency": {
            "label": "DXVK Low Latency",
            "description": "Enable the alternative dxvk-low-latency fork, which enhances DXVK with low-latency frame pacing capabilities to improve game responsiveness and input lag.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_DXVK_LOWLATENCY", "", "", ""),
        },
        "proton_vkd3d_bratan": {
            "label": "VKD3D Bratan",
            "description": "Use the vkd3d-bratan fork as the VKD3D replacement, which includes additional patches and optimizations for DX12 games.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_VKD3D_BRATAN", "", "", ""),
        },
        "proton_vkd3d_heap": {
            "label": "VKD3D Heap",
            "description": "Enable alternative VKD3D heap allocation strategy, which may improve performance or stability in some DX12 games.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_VKD3D_HEAP", "", "", ""),
        },
        "disable_layer_mesa_anti_lag": {
            "label": "Disable Mesa Anti-Lag Layer",
            "description": "Disable the Mesa Anti-Lag Vulkan layer.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "DISABLE_LAYER_MESA_ANTI_LAG", "", "", ""),
        },
        "proton_dlss_upgrade": {
            "label": "DLSS Upgrade",
            "description": "Automatically download and use newer versions of nvngx_dlss DLLs. Set to 1 for latest, or specify a version like 310.2. Also sets DXVK_NVAPI_DRS_SETTINGS to latest preset.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_DLSS_UPGRADE", "", "", ""),
        },
        "proton_dlss_indicator": {
            "label": "DLSS Indicator",
            "description": "Enable the DLSS overlay at the bottom left portion of the screen.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_DLSS_INDICATOR", "", "", ""),
        },
        "proton_xess_upgrade": {
            "label": "XeSS Upgrade",
            "description": "Enable XeSS upgrade.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_XESS_UPGRADE", "", "", ""),
        },
        "proton_fsr3_upgrade": {
            "label": "FSR3 Upgrade",
            "description": "Enable FSR3 upgrade.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_FSR3_UPGRADE", "", "", ""),
        },
        "proton_fsr4_upgrade": {
            "label": "FSR4 Upgrade",
            "description": "Automatically download amdxcffx64.dll and upgrade games with FSR 3.1 to use FSR 4. Set to 1 for latest version, or specify a version like 4.0.1.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_FSR4_UPGRADE", "", "", ""),
        },
        "proton_fsr4_indicator": {
            "label": "FSR4 Indicator",
            "description": "Enable the FSR4 watermark at the top left portion of the screen. Shorthand for setting FSR4_WATERMARK=1 and MLFG_WATERMARK=1.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_FSR4_INDICATOR", "", "", ""),
        },
        "fsr4_watermark": {
            "label": "FSR4 Watermark",
            "description": "Standalone FSR4 watermark at the top left of the screen to verify FSR4 is active. Only available on Proton-EM 10.0-2F and higher.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "FSR4_WATERMARK", "", "", ""),
        },
        "proton_fsr4_rdna3_upgrade": {
            "label": "FSR4 RDNA3 Upgrade",
            "description": "Identical to FSR4 Upgrade but for RDNA3 GPUs. Enables required compatibility options and downloads version 4.0.0 of the DLL by default.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_FSR4_RDNA3_UPGRADE", "", "", ""),
        },
        "proton_mlfg_upgrade": {
            "label": "MLFG Upgrade",
            "description": "Enables the use of MLFG when amdxcffx64.dll >= 4.0.3. Automatically enabled with FSR4 Upgrade options. Set to 0 to disable while still using FSR4.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_MLFG_UPGRADE", "", "", ""),
        },
        "mlfg_watermark": {
            "label": "MLFG Watermark",
            "description": "Standalone MLFG watermark to verify redstone frame generation is active. Only available on Proton-EM 10.0-33 and higher.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "MLFG_WATERMARK", "", "", ""),
        },
        "proton_no_d3d11": {
            "label": "No D3D11",
            "description": "Disable d3d11.dll, for d3d11 games which can fall back to and run better with d3d9.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_D3D11", "", "", ""),
        },
        "proton_no_d3d10": {
            "label": "No D3D10",
            "description": "Disable d3d10.dll and dxgi.dll, for d3d10 games which can fall back to and run better with d3d9.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_D3D10", "", "", ""),
        },
        "wine_fullscreen_integer_scaling": {
            "label": "Fullscreen Integer Scaling",
            "description": "Enable integer scaling mode, to give sharp pixels when upscaling.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "WINE_FULLSCREEN_INTEGER_SCALING", "", "", ""),
        },
        "wine_do_not_create_dxgi_device_manager": {
            "label": "No DXGI Device Manager",
            "description": "Enable hack to work around video issues in some games due to incomplete IMFDXGIDeviceManager support.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER", "", "", ""),
        },
        "wine_cpu_topology": {
            "label": "CPU Topology",
            "description": "Override the CPU topology reported to the game. Format: COUNT:ID0,ID1,... (e.g. 8:0,1,2,3,4,5,6,7). Useful for high thread-count CPUs or X3D chips to limit visible cores.",
            "inputs": "value=topology string",
            "output": ("environment_variable", "WINE_CPU_TOPOLOGY", "", "", ""),
        },
        "wine_logical_cpus_as_cores": {
            "label": "Logical CPUs as Cores",
            "description": "Report all logical CPUs (hyperthreads) as physical cores to the game.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "WINE_LOGICAL_CPUS_AS_CORES", "", "", ""),
        },
        "proton_use_wow64": {
            "label": "WoW64",
            "description": "Use WoW64 mode for running 32-bit applications. Note: incompatible with NVIDIA alternative libraries.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_USE_WOW64", "", "", ""),
        },
        "proton_disable_hidraw": {
            "label": "Disable Hidraw",
            "description": "Disable hidraw input device access. Can help with controller detection issues.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_DISABLE_HIDRAW", "", "", ""),
        },
        "proton_no_esync": {
            "label": "No Esync",
            "description": "Do not use eventfd-based in-process synchronization primitives.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_ESYNC", "", "", ""),
        },
        "proton_no_fsync": {
            "label": "No Fsync",
            "description": "Do not use futex-based in-process synchronization primitives. Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_FSYNC", "", "", ""),
        },
        "proton_use_ntsync": {
            "label": "NTSync",
            "description": "Enable the use of the in-process synchronization method. You will need to have loaded the ntsync module beforehand.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_USE_NTSYNC", "", "", ""),
        },
        "proton_no_ntsync": {
            "label": "No NTSync",
            "description": "Disable NTSync synchronization primitives even if the ntsync kernel module is loaded. Takes precedence over NTSync.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_NTSYNC", "", "", ""),
        },
        "proton_use_writecopy": {
            "label": "Write Copy",
            "description": "Enable write copy memory protection handling. May fix certain copy-protection schemes or games that rely on specific memory protection behavior.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_USE_WRITECOPY", "", "", ""),
        },
        "proton_disable_nvapi": {
            "label": "Disable NVAPI",
            "description": "Disable NVIDIA's NVAPI GPU support library.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_DISABLE_NVAPI", "", "", ""),
        },
        "proton_force_nvapi": {
            "label": "Force NVAPI",
            "description": "Force enable NVAPI even on non-Nvidia GPUs. Allows games that require NVAPI to run on AMD or Intel hardware by spoofing an Nvidia adapter.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_FORCE_NVAPI", "", "", ""),
        },
        "proton_hide_nvidia_gpu": {
            "label": "Hide NVIDIA GPU",
            "description": "Force Nvidia GPUs to always be reported as AMD GPUs. Some games require this if they depend on Windows-only Nvidia driver functionality.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_HIDE_NVIDIA_GPU", "", "", ""),
        },
        "proton_hide_vangogh_gpu": {
            "label": "Hide Van Gogh GPU",
            "description": "Force AMD Van Gogh integrated GPUs (as found in the Steam Deck) to be reported as a different GPU model.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_HIDE_VANGOGH_GPU", "", "", ""),
        },
        "proton_hide_intel_gpu": {
            "label": "Hide Intel GPU",
            "description": "Hide Intel GPU from the game. Useful for systems with both Intel and discrete GPUs where the game incorrectly selects the integrated adapter.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_HIDE_INTEL_GPU", "", "", ""),
        },
        "proton_hide_apu": {
            "label": "Hide APU",
            "description": "Hide the APU's integrated graphics from the game. Useful on systems where the game incorrectly selects the APU over a discrete GPU.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_HIDE_APU", "", "", ""),
        },
        "proton_nvidia_libs": {
            "label": "NVIDIA Libraries",
            "description": "Enable alternative implementations of Nvidia libraries missing from Proton. Allows hardware-accelerated PhysX to function. Enables nvcuda, nvenc, nvml and nvoptix. Incompatible with wow64.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NVIDIA_LIBS", "", "", ""),
        },
        "proton_nvidia_libs_no_32bit": {
            "label": "NVIDIA Libraries No 32-Bit",
            "description": "Enable only the 64-bit nvidia libraries. Useful for RTX 4000 or 5000 GPUs with bad performance or crashes when enabling nvidia libs with 32-bit games.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NVIDIA_LIBS_NO_32BIT", "", "", ""),
        },
        "proton_nvidia_nvcuda": {
            "label": "NVIDIA nvcuda",
            "description": "Enable alternative nvcuda.dll only.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NVIDIA_NVCUDA", "", "", ""),
        },
        "proton_nvidia_nvenc": {
            "label": "NVIDIA nvenc",
            "description": "Enable alternative nvencodeapi DLL only.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NVIDIA_NVENC", "", "", ""),
        },
        "proton_nvidia_nvml": {
            "label": "NVIDIA nvml",
            "description": "Enable alternative nvml.dll only. Enabled by default.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NVIDIA_NVML", "", "", ""),
        },
        "proton_nvidia_nvoptix": {
            "label": "NVIDIA nvoptix",
            "description": "Enable alternative nvoptix.dll only.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NVIDIA_NVOPTIX", "", "", ""),
        },
        "proton_native_ags": {
            "label": "Native AGS",
            "description": "Enable native AMD AGS library support. Uses the native atiadlxx and atidxx64 alongside native amd_ags_x64 for games that rely on AMD GPU Services.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NATIVE_AGS", "", "", ""),
        },
        "proton_no_wm_decoration": {
            "label": "No WM Decoration",
            "description": "Disable window decorations by the window manager, use Wine's own window decorations.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_WM_DECORATION", "", "", ""),
        },
        "proton_enable_wayland": {
            "label": "Wayland",
            "description": "Enable Wayland support. If Electron/CEF apps don't work, try adding --in-process-gpu to the command arguments. Run Steam with -steamos3 for Steam Input support.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_ENABLE_WAYLAND", "", "", ""),
        },
        "proton_enable_hdr": {
            "label": "HDR",
            "description": "Enable HDR support.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_ENABLE_HDR", "", "", ""),
        },
        "proton_prefer_sdl": {
            "label": "Prefer SDL Input",
            "description": "Prefer SDL for input handling.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_PREFER_SDL", "", "", ""),
        },
        "proton_no_steaminput": {
            "label": "No Steam Input",
            "description": "Disable Steam Input.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_STEAMINPUT", "", "", ""),
        },
        "proton_use_xalia": {
            "label": "Xalia",
            "description": "Enable Xalia, a program that can add a gamepad UI for some keyboard/mouse interfaces. The default is to enable it dynamically based on window contents.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_USE_XALIA", "", "", ""),
        },
        "proton_no_xim": {
            "label": "No XIM",
            "description": "Do not attempt to use XIM (X Input Methods) support. Enabled by default. XIM support is known to cause crashes with libx11 older than version 1.7.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_NO_XIM", "", "", ""),
        },
        "proton_force_large_address_aware": {
            "label": "Force Large Address Aware",
            "description": "Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_FORCE_LARGE_ADDRESS_AWARE", "", "", ""),
        },
        "wine_large_address_aware": {
            "label": "Large Address Aware (Wine)",
            "description": "Directly control the LARGE_ADDRESS_AWARE flag in Wine. Set to 1 to allow 32-bit apps to use more than 2 GB of RAM, or 0 to disable. PROTON_FORCE_LARGE_ADDRESS_AWARE sets this automatically; use this for manual override.",
            "inputs": "1=enable, 0=disable",
            "output": ("environment_variable", "WINE_LARGE_ADDRESS_AWARE", "", "", ""),
        },
        "proton_heap_delay_free": {
            "label": "Heap Delay Free",
            "description": "Delay freeing some memory, to work around application use-after-free bugs.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_HEAP_DELAY_FREE", "", "", ""),
        },
        "proton_heap_zero_memory": {
            "label": "Heap Zero Memory",
            "description": "Zero out heap memory on allocation. May fix games that incorrectly rely on zeroed memory behavior, at the cost of increased CPU overhead.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_HEAP_ZERO_MEMORY", "", "", ""),
        },
        "proton_set_game_drive": {
            "label": "Game Drive",
            "description": "Create an S: drive which points to the Steam Library which contains the game.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_SET_GAME_DRIVE", "", "", ""),
        },
        "proton_set_steam_drive": {
            "label": "Steam Drive",
            "description": "Create an S: drive pointing to the root of the Steam installation directory.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_SET_STEAM_DRIVE", "", "", ""),
        },
        "proton_limit_resolutions": {
            "label": "Limit Resolutions",
            "description": "Limit the number of display resolution modes reported to the game. Some older games crash or behave incorrectly when too many modes are available. Common values: 16 for very limited, 32 for moderate.",
            "inputs": "16=very limited, 32=moderate, value=custom count",
            "output": ("environment_variable", "PROTON_LIMIT_RESOLUTIONS", "", "", ""),
        },
        "proton_local_shader_cache": {
            "label": "Local Shader Cache",
            "description": "Enable per-game shader cache even if Shader Pre-caching is disabled. Shaders are cached under <steamlibrary>/shadercache/<appid>.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_LOCAL_SHADER_CACHE", "", "", ""),
        },
        "wine_block_hosts": {
            "label": "Wine Block Hosts",
            "description": "Provides a list of hosts for Wine to not connect to. Comma or semicolon separated. Maximum 16 hosts, 256 characters each.",
            "inputs": "value=host list",
            "output": ("environment_variable", "WINE_BLOCK_HOSTS", "", "", ""),
        },
        "steamdeck": {
            "label": "Steam Deck",
            "description": "Make the game believe it is running on a Steam Deck. Sets the SteamDeck environment variable to 1, enabling Steam Deck-specific code paths and optimizations in supported games.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "SteamDeck", "", "", ""),
        },
        "proton_enable_mediaconv": {
            "label": "Media Conversion",
            "description": "Enable media conversion. For debugging purposes.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_ENABLE_MEDIACONV", "", "", ""),
        },
        "proton_media_use_gst": {
            "label": "Media Use GStreamer",
            "description": "Fixes video/audio playback in cutscenes in some cases.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_MEDIA_USE_GST", "", "", ""),
        },
        "proton_gst_video_orientation": {
            "label": "GStreamer Video Orientation",
            "description": "Change the orientation (rotation) of videos rendered using GStreamer. Uses gstreamer's videoflip plugin values.",
            "inputs": "value=orientation value",
            "output": ("environment_variable", "PROTON_GST_VIDEO_ORIENTATION", "", "", ""),
        },
        "gst_gl_window": {
            "label": "GStreamer GL Window",
            "description": "GStreamer GL window backend.",
            "inputs": "value=window backend",
            "output": ("environment_variable", "GST_GL_WINDOW", "", "", ""),
        },
        "fna3d_force_driver": {
            "label": "FNA3D Force Driver",
            "description": "Force FNA to use a specific driver for rendering.",
            "inputs": "D3D11=d3d11",
            "output": ("environment_variable", "FNA3D_FORCE_DRIVER", "", "", ""),
        },
        "winealsa_channels": {
            "label": "WINEALSA Channels",
            "description": "Select more than two channels with the winealsa driver or force disable spatial audio. Use 2 to disable spatial audio, 4 for 2 front + 2 rear, 6 for 5.1, 8 for 7.1.",
            "inputs": "2=2, 4=4, 6=5.1, 8=7.1",
            "output": ("environment_variable", "WINEALSA_CHANNELS", "", "", ""),
        },
        "winealsa_spatial": {
            "label": "WINEALSA Spatial",
            "description": "Properly downmixes spatial with winealsa and includes the height channels. Recommended only if there are spatial audio errors with the WINEALSA_CHANNELS variable.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "WINEALSA_SPATIAL", "", "", ""),
        },
        "winepulse_fast_polling": {
            "label": "WINEPULSE Fast Polling",
            "description": "Can help eliminate crackling with the default audio driver.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "WINEPULSE_FAST_POLLING", "", "", ""),
        },
        "proton_log": {
            "label": "Proton Log",
            "description": "Dump a useful debug log to $PROTON_LOG_DIR/steam-$APPID.log. Set to 1 for default logging, or set to a string to append to the default WINEDEBUG channels. For video/audio issues, use +mfplat,+quartz,+wmvcore,+wmadec,+dmo instead of 1.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_LOG", "", "", ""),
        },
        "proton_log_directory": {
            "label": "Proton Log Directory",
            "description": "Output log files into the specified directory. Defaults to your home directory.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "PROTON_LOG_DIR", "", "", ""),
        },
        "proton_wait_attach": {
            "label": "Proton Wait Attach",
            "description": "Wait for a debugger to attach to steam.exe before launching the game process.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "PROTON_WAIT_ATTACH", "", "", ""),
        },
        "proton_crash_report_directory": {
            "label": "Proton Crash Report Directory",
            "description": "Write crash logs into this directory. Does not clean up old logs.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "PROTON_CRASH_REPORT_DIR", "", "", ""),
        },
    }
