def get_render_settings() -> dict:
    return {
        "_tab_metadata": (True,),
        "opengl_rendering_device": {
            "label": "OpenGL Rendering Device",
            "description": "GPU used for OpenGL rendering. Enter the index number shown next to the detected device. Only index values are accepted; any other input is ignored. Use 'unset' to clear all OpenGL render env vars.",
            "inputs": "dynamic",
            "output": (
                ("environment_variable", "__GLX_VENDOR_LIBRARY_NAME", "", "", ""),
                ("environment_variable", "__EGL_VENDOR_LIBRARY_FILENAMES", "", "", ":"),
                ("environment_variable", "__EGL_VENDOR_LIBRARY_DIRS", "", "", ":"),
                ("environment_variable", "__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS", "", "", ""),
                ("environment_variable", "EGL_DRIVER", "", "", ""),
                ("environment_variable", "EGL_PLATFORM", "", "", ""),
                ("environment_variable", "EGL_SOFTWARE", "", "", ""),
                ("environment_variable", "EGL_DRIVERS_PATH", "", "", ":"),
                ("environment_variable", "MESA_LOADER_DRIVER_OVERRIDE", "", "", ""),
                ("environment_variable", "GALLIUM_DRIVER", "", "", ""),
                ("environment_variable", "GALLIUM_PIPE_SEARCH_DIR", "", "", ""),
                ("environment_variable", "dri_driver", "", "", ""),
                ("environment_variable", "DRI_PRIME", "", "", ""),
                ("environment_variable", "DRI_PRIME_DEBUG", "", "", ""),
                ("environment_variable", "LIBGL_ALWAYS_SOFTWARE", "", "", ""),
                ("environment_variable", "LIBGL_ALWAYS_INDIRECT", "", "", ""),
                ("environment_variable", "LIBGL_DRIVERS_PATH", "", "", ":"),
                ("environment_variable", "LIBGL_DRI2_DISABLE", "", "", ""),
                ("environment_variable", "LIBGL_DRI3_DISABLE", "", "", ""),
                ("environment_variable", "LIBGL_KOPPER_DRI2", "", "", ""),
                ("environment_variable", "LIBGL_KOPPER_DISABLE", "", "", ""),
                ("environment_variable", "force_direct_glx_context", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "", "", ""),
                ("environment_variable", "DISABLE_LAYER_NV_OPTIMUS_1", "", "", ""),
                ("environment_variable", "NVIDIA_VISIBLE_DEVICES", "", "", ","),
                ("environment_variable", "DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1", "", "", ""),
                ("environment_variable", "INTEL_FORCE_PROBE", "", "", ","),
                ("environment_variable", "INTEL_NO_HW", "", "", ""),
                ("environment_variable", "PAN_GPU_ID", "", "", ""),
                ("environment_variable", "V3D_SIMULATOR_FILE", "", "", ""),
                ("environment_variable", "device_id", "", "", ""),
                ("environment_variable", "NODEVICE_SELECT", "", "", ""),
                ("environment_variable", "DRAW_USE_LLVM", "", "", ""),
                ("environment_variable", "DRAW_FSE", "", "", ""),
                ("environment_variable", "DRAW_NO_FSE", "", "", ""),
                ("environment_variable", "SOFTPIPE_USE_LLVM", "", "", ""),
                ("environment_variable", "SVGA_FORCE_SWTNL", "", "", ""),
                ("environment_variable", "SVGA_NO_SWTNL", "", "", ""),
                ("environment_variable", "ZINK_USE_LAVAPIPE", "", "", ""),
            ),
        },
        "vulkan_rendering_device": {
            "label": "Vulkan Rendering Device",
            "description": "GPU used for Vulkan rendering. Enter the index number shown next to the detected device. Only index values are accepted; any other input is ignored. Use 'unset' to clear all Vulkan render env vars.",
            "inputs": "dynamic",
            "output": (
                ("environment_variable", "MESA_VK_DEVICE_SELECT", "", "", ""),
                ("environment_variable", "MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE", "", "", ""),
                ("environment_variable", "MESA_VK_DEVICE_SELECT_DEBUG", "", "", ""),
                ("environment_variable", "VK_ICD_FILENAMES", "", "", ":"),
                ("environment_variable", "VK_DRIVER_FILES", "", "", ":"),
                ("environment_variable", "VK_ADD_DRIVER_FILES", "", "", ":"),
                ("environment_variable", "VK_DRIVERS_PATH", "", "", ":"),
                ("environment_variable", "VK_LOADER_DRIVERS_SELECT", "", "", ":"),
                ("environment_variable", "VK_LOADER_DRIVERS_DISABLE", "", "", ":"),
                ("environment_variable", "VK_LOADER_DRIVER_ID_FILTER", "", "", ","),
                ("environment_variable", "VK_LOADER_DEVICE_ID_FILTER", "", "", ","),
                ("environment_variable", "VK_LOADER_VENDOR_ID_FILTER", "", "", ","),
                ("environment_variable", "VK_LOADER_DISABLE_SELECT", "", "", ""),
                ("environment_variable", "VK_DEVSIM_FILENAME", "", "", ""),
                ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE", "", "", ""),
                ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE_NAME", "", "", ""),
                ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE_UUID", "", "", ""),
                ("environment_variable", "AMD_VULKAN_ICD", "", "", ""),
                ("environment_variable", "DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1", "", "", ""),
                ("environment_variable", "AMDVLK_ENABLE_DEVELOPING_EXT", "", "", ""),
                ("environment_variable", "RADV_FORCE_FAMILY", "", "", ""),
                ("environment_variable", "__VK_LAYER_NV_optimus", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "", "", ""),
                ("environment_variable", "DISABLE_LAYER_NV_OPTIMUS_1", "", "", ""),
                ("environment_variable", "NVIDIA_VISIBLE_DEVICES", "", "", ","),
                ("environment_variable", "INTEL_FORCE_PROBE", "", "", ","),
                ("environment_variable", "DRI_PRIME", "", "", ""),
                ("environment_variable", "DRI_PRIME_DEBUG", "", "", ""),
                ("environment_variable", "VULKAN_DEVICE_INDEX", "", "", ""),
                ("environment_variable", "ENABLE_DEVICE_CHOOSER_LAYER", "", "", ""),
                ("environment_variable", "NODEVICE_SELECT", "", "", ""),
                ("environment_variable", "device_id", "", "", ""),
                ("environment_variable", "force_vk_vendor", "", "", ""),
                ("environment_variable", "anv_force_vk_vendor", "", "", ""),
                ("environment_variable", "PAN_GPU_ID", "", "", ""),
                ("environment_variable", "V3D_SIMULATOR_FILE", "", "", ""),
                ("environment_variable", "PVR_SHIM_DEVICE_BVNC", "", "", ""),
                ("environment_variable", "dzn_disable", "", "", ""),
                ("environment_variable", "ZINK_USE_LAVAPIPE", "", "", ""),
                ("environment_variable", "MESA_D3D12_DEFAULT_ADAPTER_NAME", "", "", ""),
            ),
        },
        "glx_vendor_library_name": {
            "label": "GLX Vendor Library Name",
            "description": "GLX vendor library. Use 'nvidia' for NVIDIA proprietary, 'mesa' for Mesa.",
            "inputs": "nvidia=nvidia, mesa=mesa",
            "output": ("environment_variable", "__GLX_VENDOR_LIBRARY_NAME", "", "", ""),
        },
        "nv_prime_render_offload": {
            "label": "NV PRIME Render Offload",
            "description": "NVIDIA PRIME render offload. Typically paired with GLX Vendor Library Name=nvidia.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD", "", "", ""),
        },
        "nv_prime_render_offload_provider": {
            "label": "NV PRIME Render Offload Provider",
            "description": "Name of the NVIDIA PRIME provider (e.g. NVIDIA-G0).",
            "inputs": "value=provider name",
            "output": ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "", "", ""),
        },
        "nv_optimus_layer": {
            "label": "NV Optimus Layer",
            "description": "NV Optimus Vulkan layer.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "DISABLE_LAYER_NV_OPTIMUS_1", "", "", ""),
        },
        "nvidia_visible_devices": {
            "label": "NVIDIA Visible Devices",
            "description": "Restrict NVIDIA GPUs visible to the application. Comma-separated list of UUIDs or 'all'.",
            "inputs": "value=uuid list or 'all'",
            "output": ("environment_variable", "NVIDIA_VISIBLE_DEVICES", "", "", ""),
        },
        "vk_layer_nv_optimus": {
            "label": "VK Layer NV Optimus",
            "description": "NV Optimus Vulkan layer activation for NVIDIA PRIME.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "__VK_LAYER_NV_optimus", "", "", ""),
        },
        "amd_switchable_graphics_layer": {
            "label": "AMD Switchable Graphics Layer",
            "description": "AMD switchable graphics Vulkan layer.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1", "", "", ""),
        },
        "amd_vulkan_icd": {
            "label": "AMD Vulkan ICD",
            "description": "AMD Vulkan driver. RADV for open-source, AMDVLK for closed-source.",
            "inputs": "RADV=RADV, AMDVLK=AMDVLK",
            "output": ("environment_variable", "AMD_VULKAN_ICD", "", "", ""),
        },
        "amdvlk_developing_ext": {
            "label": "AMDVLK Developing Extensions",
            "description": "Experimental extensions in AMDVLK.",
            "inputs": "all=all, value=extension name",
            "output": ("environment_variable", "AMDVLK_ENABLE_DEVELOPING_EXT", "", "", ""),
        },
        "radv_force_family": {
            "label": "RADV Force Family",
            "description": "Force RADV to emulate a specific GPU family.",
            "inputs": "value=family name",
            "output": ("environment_variable", "RADV_FORCE_FAMILY", "", "", ""),
        },
        "intel_force_probe": {
            "label": "Intel Force Probe",
            "description": "Force the Intel driver to probe specific PCI device IDs. Comma-separated hex values, prefix with ! to exclude.",
            "inputs": "value=pci id(s)",
            "output": ("environment_variable", "INTEL_FORCE_PROBE", "", "", ""),
        },
        "intel_hardware": {
            "label": "Intel Hardware",
            "description": "Intel hardware submission. When off, runs software-only for debugging.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "INTEL_NO_HW", "", "", ""),
        },
        "force_vk_vendor": {
            "label": "Force Vulkan Vendor",
            "description": "Override the Vulkan vendor ID reported to the application.",
            "inputs": "value=vendor id",
            "output": ("environment_variable", "force_vk_vendor", "", "", ""),
        },
        "anv_force_vk_vendor": {
            "label": "ANV Force Vulkan Vendor",
            "description": "Override the Vulkan vendor ID reported by ANV.",
            "inputs": "value=vendor id",
            "output": ("environment_variable", "anv_force_vk_vendor", "", "", ""),
        },
        "dri_prime": {
            "label": "DRI PRIME",
            "description": "Select the Mesa PRIME device by index. 0 = primary, 1 = secondary, etc.",
            "inputs": "0=0, 1=1, 2=2, 3=3",
            "output": ("environment_variable", "DRI_PRIME", "", "", ""),
        },
        "dri_prime_debug": {
            "label": "DRI PRIME Debug",
            "description": "Debug output for DRI PRIME.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "DRI_PRIME_DEBUG", "", "", ""),
        },
        "dri_driver": {
            "label": "DRI Driver",
            "description": "Override the DRI driver name.",
            "inputs": "value=driver name",
            "output": ("environment_variable", "dri_driver", "", "", ""),
        },
        "mesa_loader_driver_override": {
            "label": "Mesa Loader Driver Override",
            "description": "Override the Mesa loader driver (e.g. zink, iris, radeonsi).",
            "inputs": "zink=zink, iris=iris, radeonsi=radeonsi, i965=i965",
            "output": ("environment_variable", "MESA_LOADER_DRIVER_OVERRIDE", "", "", ""),
        },
        "gallium_driver": {
            "label": "Gallium Driver",
            "description": "Override the Gallium driver (e.g. llvmpipe, softpipe, zink).",
            "inputs": "llvmpipe=llvmpipe, softpipe=softpipe, zink=zink",
            "output": ("environment_variable", "GALLIUM_DRIVER", "", "", ""),
        },
        "gallium_pipe_search_dir": {
            "label": "Gallium Pipe Search Dir",
            "description": "Directory to search for Gallium pipe drivers.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "GALLIUM_PIPE_SEARCH_DIR", "", "", ""),
        },
        "libgl_always_software": {
            "label": "LibGL Always Software",
            "description": "Force software OpenGL rendering.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "LIBGL_ALWAYS_SOFTWARE", "", "", ""),
        },
        "libgl_always_indirect": {
            "label": "LibGL Always Indirect",
            "description": "Force indirect GLX rendering.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "LIBGL_ALWAYS_INDIRECT", "", "", ""),
        },
        "libgl_drivers_path": {
            "label": "LibGL Drivers Path",
            "description": "Search path for LibGL DRI drivers.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "LIBGL_DRIVERS_PATH", "", "", ""),
        },
        "libgl_dri2": {
            "label": "LibGL DRI2",
            "description": "DRI2 extension in LibGL.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "LIBGL_DRI2_DISABLE", "", "", ""),
        },
        "libgl_dri3": {
            "label": "LibGL DRI3",
            "description": "DRI3 extension in LibGL.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "LIBGL_DRI3_DISABLE", "", "", ""),
        },
        "libgl_kopper_dri2": {
            "label": "LibGL Kopper DRI2",
            "description": "DRI2 path in the Kopper WSI loader.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "LIBGL_KOPPER_DRI2", "", "", ""),
        },
        "libgl_kopper": {
            "label": "LibGL Kopper",
            "description": "Kopper WSI loader in LibGL.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "LIBGL_KOPPER_DISABLE", "", "", ""),
        },
        "force_direct_glx_context": {
            "label": "Force Direct GLX Context",
            "description": "Force direct GLX rendering contexts.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "force_direct_glx_context", "", "", ""),
        },
        "egl_driver": {
            "label": "EGL Driver",
            "description": "Override the EGL driver.",
            "inputs": "value=driver name",
            "output": ("environment_variable", "EGL_DRIVER", "", "", ""),
        },
        "egl_platform": {
            "label": "EGL Platform",
            "description": "Override the EGL platform (x11, wayland, gbm, surfaceless).",
            "inputs": "x11=x11, wayland=wayland, gbm=gbm, surfaceless=surfaceless",
            "output": ("environment_variable", "EGL_PLATFORM", "", "", ""),
        },
        "egl_software": {
            "label": "EGL Software",
            "description": "Force software EGL rendering.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "EGL_SOFTWARE", "", "", ""),
        },
        "egl_drivers_path": {
            "label": "EGL Drivers Path",
            "description": "Search path for EGL driver libraries.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "EGL_DRIVERS_PATH", "", "", ""),
        },
        "egl_vendor_library_filenames": {
            "label": "EGL Vendor Library Filenames",
            "description": "Colon-separated list of EGL vendor library JSON filenames.",
            "inputs": "value=filename(s)",
            "output": ("environment_variable", "__EGL_VENDOR_LIBRARY_FILENAMES", "", "", ""),
        },
        "egl_vendor_library_dirs": {
            "label": "EGL Vendor Library Dirs",
            "description": "Colon-separated search path for EGL vendor library JSON files.",
            "inputs": "value=directory path(s)",
            "output": ("environment_variable", "__EGL_VENDOR_LIBRARY_DIRS", "", "", ""),
        },
        "egl_external_platform_config_dirs": {
            "label": "EGL External Platform Config Dirs",
            "description": "Search path for EGL external platform config files.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS", "", "", ""),
        },
        "mesa_vk_device_select": {
            "label": "MESA VK Device Select",
            "description": "Mesa Vulkan device selection. Use 'vendorID:deviceID' or 'list' to print candidates.",
            "inputs": "value=vendor:device or 'list'",
            "output": ("environment_variable", "MESA_VK_DEVICE_SELECT", "", "", ""),
        },
        "mesa_vk_device_select_force_default_device": {
            "label": "MESA VK Device Select Force Default",
            "description": "Force Mesa device select to pick the default device.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE", "", "", ""),
        },
        "mesa_vk_device_select_debug": {
            "label": "MESA VK Device Select Debug",
            "description": "Debug output for Mesa device select layer.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "MESA_VK_DEVICE_SELECT_DEBUG", "", "", ""),
        },
        "vk_icd_filenames": {
            "label": "VK ICD Filenames (legacy)",
            "description": "Legacy colon-separated list of Vulkan ICD JSON files.",
            "inputs": "value=filename(s)",
            "output": ("environment_variable", "VK_ICD_FILENAMES", "", "", ""),
        },
        "vk_driver_files": {
            "label": "VK Driver Files",
            "description": "Colon-separated list of Vulkan driver JSON files (replaces ICD discovery).",
            "inputs": "value=filename(s)",
            "output": ("environment_variable", "VK_DRIVER_FILES", "", "", ""),
        },
        "vk_add_driver_files": {
            "label": "VK Add Driver Files",
            "description": "Colon-separated list of additional Vulkan driver JSON files.",
            "inputs": "value=filename(s)",
            "output": ("environment_variable", "VK_ADD_DRIVER_FILES", "", "", ""),
        },
        "vk_drivers_path": {
            "label": "VK Drivers Path",
            "description": "Search path for Vulkan driver manifest files.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "VK_DRIVERS_PATH", "", "", ""),
        },
        "vk_loader_drivers_select": {
            "label": "VK Loader Drivers Select",
            "description": "Allow only matching Vulkan drivers to load.",
            "inputs": "value=driver name pattern(s)",
            "output": ("environment_variable", "VK_LOADER_DRIVERS_SELECT", "", "", ""),
        },
        "vk_loader_drivers_suppressed": {
            "label": "VK Loader Drivers Suppressed",
            "description": "Vulkan drivers matching this pattern are suppressed.",
            "inputs": "value=driver name pattern(s)",
            "output": ("environment_variable", "VK_LOADER_DRIVERS_DISABLE", "", "", ""),
        },
        "vk_loader_driver_id_filter": {
            "label": "VK Loader Driver ID Filter",
            "description": "Filter Vulkan drivers by driver ID.",
            "inputs": "value=driver id",
            "output": ("environment_variable", "VK_LOADER_DRIVER_ID_FILTER", "", "", ""),
        },
        "vk_loader_device_id_filter": {
            "label": "VK Loader Device ID Filter",
            "description": "Filter Vulkan devices by device ID.",
            "inputs": "value=device id",
            "output": ("environment_variable", "VK_LOADER_DEVICE_ID_FILTER", "", "", ""),
        },
        "vk_loader_vendor_id_filter": {
            "label": "VK Loader Vendor ID Filter",
            "description": "Filter Vulkan devices by vendor ID.",
            "inputs": "value=vendor id",
            "output": ("environment_variable", "VK_LOADER_VENDOR_ID_FILTER", "", "", ""),
        },
        "vk_loader_device_selection": {
            "label": "VK Loader Device Selection",
            "description": "Loader-side Vulkan device selection.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "VK_LOADER_DISABLE_SELECT", "", "", ""),
        },
        "vk_devsim_filename": {
            "label": "VK DevSim Filename",
            "description": "Path to a device simulation JSON file.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "VK_DEVSIM_FILENAME", "", "", ""),
        },
        "vk_khronos_profiles_force_device": {
            "label": "VK Khronos Profiles Force Device",
            "description": "Force the Khronos profiles layer to use a specific device.",
            "inputs": "value=device spec",
            "output": ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE", "", "", ""),
        },
        "vk_khronos_profiles_force_device_name": {
            "label": "VK Khronos Profiles Force Device Name",
            "description": "Force Khronos profiles layer device by name.",
            "inputs": "value=device name",
            "output": ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE_NAME", "", "", ""),
        },
        "vk_khronos_profiles_force_device_uuid": {
            "label": "VK Khronos Profiles Force Device UUID",
            "description": "Force Khronos profiles layer device by UUID.",
            "inputs": "value=device uuid",
            "output": ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE_UUID", "", "", ""),
        },
        "vulkan_device_index": {
            "label": "Vulkan Device Index",
            "description": "Vulkan device by index (used by some games and chooser layers).",
            "inputs": "0=0, 1=1, 2=2, 3=3",
            "output": ("environment_variable", "VULKAN_DEVICE_INDEX", "", "", ""),
        },
        "device_chooser_layer": {
            "label": "Device Chooser Layer",
            "description": "Vulkan device chooser layer.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "ENABLE_DEVICE_CHOOSER_LAYER", "", "", ""),
        },
        "device_select": {
            "label": "Device Select",
            "description": "Vulkan device selection logic.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "NODEVICE_SELECT", "", "", ""),
        },
        "device_id": {
            "label": "Device ID",
            "description": "Override the reported device ID.",
            "inputs": "value=device id",
            "output": ("environment_variable", "device_id", "", "", ""),
        },
        "pan_gpu_id": {
            "label": "Panfrost GPU ID",
            "description": "Override the Panfrost GPU model ID.",
            "inputs": "value=gpu id",
            "output": ("environment_variable", "PAN_GPU_ID", "", "", ""),
        },
        "v3d_simulator_file": {
            "label": "V3D Simulator File",
            "description": "Path to the V3D simulator configuration file.",
            "inputs": "path=filesystem path",
            "output": ("environment_variable", "V3D_SIMULATOR_FILE", "", "", ""),
        },
        "pvr_shim_device_bvnc": {
            "label": "PVR Shim Device BVNC",
            "description": "Override the PVR shim reported device BVNC.",
            "inputs": "value=bvnc string",
            "output": ("environment_variable", "PVR_SHIM_DEVICE_BVNC", "", "", ""),
        },
        "dzn": {
            "label": "DZN",
            "description": "DZN Vulkan-over-D3D12 driver.",
            "inputs": "0=on, 1=off",
            "output": ("environment_variable", "dzn_disable", "", "", ""),
        },
        "zink_use_lavapipe": {
            "label": "Zink Use Lavapipe",
            "description": "Force Zink to layer on top of Lavapipe.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "ZINK_USE_LAVAPIPE", "", "", ""),
        },
        "mesa_d3d12_default_adapter_name": {
            "label": "MESA D3D12 Default Adapter Name",
            "description": "Override the default D3D12 adapter name used by Mesa.",
            "inputs": "value=adapter name",
            "output": ("environment_variable", "MESA_D3D12_DEFAULT_ADAPTER_NAME", "", "", ""),
        },
        "draw_use_llvm": {
            "label": "Draw Use LLVM",
            "description": "Force LLVM code generation in the draw module.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "DRAW_USE_LLVM", "", "", ""),
        },
        "draw_fse": {
            "label": "Draw FSE",
            "description": "Force Fixed Shader Execution in draw module.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "DRAW_FSE", "", "", ""),
        },
        "draw_no_fse": {
            "label": "Draw No FSE",
            "description": "Suppress Fixed Shader Execution in draw module.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "DRAW_NO_FSE", "", "", ""),
        },
        "softpipe_use_llvm": {
            "label": "Softpipe Use LLVM",
            "description": "LLVM backend in Softpipe.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "SOFTPIPE_USE_LLVM", "", "", ""),
        },
        "svga_force_swtnl": {
            "label": "SVGA Force SWTNL",
            "description": "Force software T&L in VMware SVGA driver.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "SVGA_FORCE_SWTNL", "", "", ""),
        },
        "svga_no_swtnl": {
            "label": "SVGA No SWTNL",
            "description": "Suppress software T&L in VMware SVGA driver.",
            "inputs": "1=on, 0=off",
            "output": ("environment_variable", "SVGA_NO_SWTNL", "", "", ""),
        },
    }
