def get_render_settings() -> dict:
    return {
        "_tab_metadata": (True,),
        "opengl_rendering_device": {
            "label": "OpenGL Rendering Device",
            "description": "GPU used for OpenGL rendering. Enter the number shown next to the detected device.",
            "inputs": "dynamic",
            "output": (
                ("environment_variable", "__GLX_VENDOR_LIBRARY_NAME", "", "", ""),
                ("environment_variable", "__EGL_VENDOR_LIBRARY_FILENAMES", "", "", ":"),
                ("environment_variable", "__EGL_VENDOR_LIBRARY_DIRS", "", "", ":"),
                ("environment_variable", "__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS", "", "", ""),
                ("environment_variable", "EGL_DRIVER", "", "", ""),
                ("environment_variable", "EGL_PLATFORM", "", "", ""),
                ("environment_variable", "EGL_SOFTWARE", "", "", ""),
                ("environment_variable", "EGL_DRIVERS_PATH", "", "", ":"),
                ("environment_variable", "MESA_LOADER_DRIVER_OVERRIDE", "", "", ""),
                ("environment_variable", "GALLIUM_DRIVER", "", "", ""),
                ("environment_variable", "GALLIUM_PIPE_SEARCH_DIR", "", "", ""),
                ("environment_variable", "dri_driver", "", "", ""),
                ("environment_variable", "DRI_PRIME", "", "", ""),
                ("environment_variable", "DRI_PRIME_DEBUG", "", "", ""),
                ("environment_variable", "LIBGL_ALWAYS_SOFTWARE", "", "", ""),
                ("environment_variable", "LIBGL_ALWAYS_INDIRECT", "", "", ""),
                ("environment_variable", "LIBGL_DRIVERS_PATH", "", "", ":"),
                ("environment_variable", "LIBGL_DRI2_DISABLE", "", "", ""),
                ("environment_variable", "LIBGL_DRI3_DISABLE", "", "", ""),
                ("environment_variable", "LIBGL_KOPPER_DRI2", "", "", ""),
                ("environment_variable", "LIBGL_KOPPER_DISABLE", "", "", ""),
                ("environment_variable", "force_direct_glx_context", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "", "", ""),
                ("environment_variable", "DISABLE_LAYER_NV_OPTIMUS_1", "", "", ""),
                ("environment_variable", "NVIDIA_VISIBLE_DEVICES", "", "", ","),
                ("environment_variable", "DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1", "", "", ""),
                ("environment_variable", "INTEL_FORCE_PROBE", "", "", ","),
                ("environment_variable", "INTEL_NO_HW", "", "", ""),
                ("environment_variable", "PAN_GPU_ID", "", "", ""),
                ("environment_variable", "V3D_SIMULATOR_FILE", "", "", ""),
                ("environment_variable", "device_id", "", "", ""),
                ("environment_variable", "NODEVICE_SELECT", "", "", ""),
                ("environment_variable", "DRAW_USE_LLVM", "", "", ""),
                ("environment_variable", "DRAW_FSE", "", "", ""),
                ("environment_variable", "DRAW_NO_FSE", "", "", ""),
                ("environment_variable", "SOFTPIPE_USE_LLVM", "", "", ""),
                ("environment_variable", "SVGA_FORCE_SWTNL", "", "", ""),
                ("environment_variable", "SVGA_NO_SWTNL", "", "", ""),
                ("environment_variable", "ZINK_USE_LAVAPIPE", "", "", ""),
            ),
        },
        "vulkan_rendering_device": {
            "label": "Vulkan Rendering Device",
            "description": "GPU used for Vulkan rendering. Enter the number shown next to the detected device.",
            "inputs": "dynamic",
            "output": (
                ("environment_variable", "MESA_VK_DEVICE_SELECT", "", "", ""),
                ("environment_variable", "MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE", "", "", ""),
                ("environment_variable", "MESA_VK_DEVICE_SELECT_DEBUG", "", "", ""),
                ("environment_variable", "VK_ICD_FILENAMES", "", "", ":"),
                ("environment_variable", "VK_DRIVER_FILES", "", "", ":"),
                ("environment_variable", "VK_ADD_DRIVER_FILES", "", "", ":"),
                ("environment_variable", "VK_DRIVERS_PATH", "", "", ":"),
                ("environment_variable", "VK_LOADER_DRIVERS_SELECT", "", "", ":"),
                ("environment_variable", "VK_LOADER_DRIVERS_DISABLE", "", "", ":"),
                ("environment_variable", "VK_LOADER_DRIVER_ID_FILTER", "", "", ","),
                ("environment_variable", "VK_LOADER_DEVICE_ID_FILTER", "", "", ","),
                ("environment_variable", "VK_LOADER_VENDOR_ID_FILTER", "", "", ","),
                ("environment_variable", "VK_LOADER_DISABLE_SELECT", "", "", ""),
                ("environment_variable", "VK_DEVSIM_FILENAME", "", "", ""),
                ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE", "", "", ""),
                ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE_NAME", "", "", ""),
                ("environment_variable", "VK_KHRONOS_PROFILES_FORCE_DEVICE_UUID", "", "", ""),
                ("environment_variable", "AMD_VULKAN_ICD", "", "", ""),
                ("environment_variable", "DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1", "", "", ""),
                ("environment_variable", "AMDVLK_ENABLE_DEVELOPING_EXT", "", "", ""),
                ("environment_variable", "RADV_FORCE_FAMILY", "", "", ""),
                ("environment_variable", "__VK_LAYER_NV_optimus", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD", "", "", ""),
                ("environment_variable", "__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "", "", ""),
                ("environment_variable", "DISABLE_LAYER_NV_OPTIMUS_1", "", "", ""),
                ("environment_variable", "NVIDIA_VISIBLE_DEVICES", "", "", ","),
                ("environment_variable", "INTEL_FORCE_PROBE", "", "", ","),
                ("environment_variable", "DRI_PRIME", "", "", ""),
                ("environment_variable", "DRI_PRIME_DEBUG", "", "", ""),
                ("environment_variable", "VULKAN_DEVICE_INDEX", "", "", ""),
                ("environment_variable", "ENABLE_DEVICE_CHOOSER_LAYER", "", "", ""),
                ("environment_variable", "NODEVICE_SELECT", "", "", ""),
                ("environment_variable", "device_id", "", "", ""),
                ("environment_variable", "force_vk_vendor", "", "", ""),
                ("environment_variable", "anv_force_vk_vendor", "", "", ""),
                ("environment_variable", "PAN_GPU_ID", "", "", ""),
                ("environment_variable", "V3D_SIMULATOR_FILE", "", "", ""),
                ("environment_variable", "PVR_SHIM_DEVICE_BVNC", "", "", ""),
                ("environment_variable", "dzn_disable", "", "", ""),
                ("environment_variable", "ZINK_USE_LAVAPIPE", "", "", ""),
                ("environment_variable", "MESA_D3D12_DEFAULT_ADAPTER_NAME", "", "", ""),
            ),
        },
    }
