def get_vkd3d_settings() -> dict:
    return {
        "_tab_metadata": (True,),
        "vkd3d_frame_rate": {
            "label": "Frame Rate Limit",
            "description": "Limit the frame rate. 0 uncaps the frame rate; any positive integer limits rendering to that many frames per second. Note: starting from vkd3d-proton v2.14+, DXVK_FRAME_RATE is no longer supported for DX12 games; only VKD3D_FRAME_RATE remains.",
            "inputs": "0=uncap, value=fps limit (e.g. 60)",
            "output": ("environment_variable", "VKD3D_FRAME_RATE", "", "", ""),
        },
        "vkd3d_vulkan_device": {
            "label": "Force Vulkan Device Index",
            "description": "Force vkd3d-proton to use a specific GPU by zero-based device index.",
            "inputs": "0=first device, 1=second device, value=device index",
            "output": ("environment_variable", "VKD3D_VULKAN_DEVICE", "", "", ""),
        },
        "vkd3d_filter_device_name": {
            "label": "Filter Device Name",
            "description": "Skip Vulkan devices whose names don't include this substring. vkd3d-proton will use the first device whose name matches.",
            "inputs": "value=device name substring",
            "output": ("environment_variable", "VKD3D_FILTER_DEVICE_NAME", "", "", ""),
        },
        "vkd3d_disable_extensions": {
            "label": "Disable Vulkan Extensions",
            "description": "Comma-separated list of Vulkan extensions that vkd3d-proton should not use even if available. Example: VK_KHR_present_id can fix black screens on some PRIME/Optimus setups.",
            "inputs": "value=comma-separated extension names (e.g. VK_KHR_present_id)",
            "output": ("environment_variable", "VKD3D_DISABLE_EXTENSIONS", "", "", ""),
        },
        "vkd3d_swapchain_present_mode": {
            "label": "Swapchain Present Mode",
            "description": "Force a specific Vulkan present mode for the swapchain if supported.",
            "inputs": "IMMEDIATE=immediate (no vsync), MAILBOX=mailbox, FIFO=fifo (vsync), FIFO_RELAXED=fifo relaxed, FIFO_LATEST_READY=fifo latest ready",
            "output": ("environment_variable", "VKD3D_SWAPCHAIN_PRESENT_MODE", "", "", ""),
        },
        "vkd3d_config_vk_debug": {
            "label": "Config: Vulkan Debug",
            "description": "Enable Vulkan debug extensions and load the validation layer.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "vk_debug", ","),
        },
        "vkd3d_config_skip_application_workarounds": {
            "label": "Config: Skip App Workarounds",
            "description": "Skip all per-application workarounds. Useful for debugging to isolate whether a workaround is causing an issue.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "skip_application_workarounds", ","),
        },
        "vkd3d_config_nodxr": {
            "label": "Config: Disable DXR",
            "description": "Disable DirectX Raytracing (DXR / ray tracing) support entirely.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "nodxr", ","),
        },
        "vkd3d_config_dxr": {
            "label": "Config: Force Enable DXR",
            "description": "Force enable DXR even when vkd3d-proton considers it unsafe. DXR is normally enabled automatically when safe.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "dxr", ","),
        },
        "vkd3d_config_dxr12": {
            "label": "Config: Experimental DXR 1.2",
            "description": "Enable experimental DXR 1.2 support if VK_EXT_opacity_micromap is available on the driver.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "dxr12", ","),
        },
        "vkd3d_config_force_static_cbv": {
            "label": "Config: Force Static CBV (NVIDIA)",
            "description": "Unsafe speed hack on NVIDIA GPUs. May or may not provide a significant performance uplift. Use at your own risk.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "force_static_cbv", ","),
        },
        "vkd3d_config_single_queue": {
            "label": "Config: Single Queue",
            "description": "Do not use asynchronous compute or transfer queues. Forces all GPU work through a single queue.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "single_queue", ","),
        },
        "vkd3d_config_no_upload_hvv": {
            "label": "Config: No Upload HVV",
            "description": "Block host-visible VRAM (large/resizable BAR) for the UPLOAD heap. May free up vital VRAM in memory-critical situations at the cost of lower GPU performance.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "no_upload_hvv", ","),
        },
        "vkd3d_config_force_host_cached": {
            "label": "Config: Force Host Cached",
            "description": "Force all host-visible allocations to be CACHED. Greatly accelerates GPU captures with RenderDoc and similar tools.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "force_host_cached", ","),
        },
        "vkd3d_config_no_invariant_position": {
            "label": "Config: No Invariant Position",
            "description": "Disable the invariant position workaround. The workaround is enabled by default to prevent Z-fighting issues.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "no_invariant_position", ","),
        },
        "vkd3d_config_no_staggered_submit": {
            "label": "Config: No Staggered Submit",
            "description": "Disable the staggered queue submission scheduling added in v2.14 for FSR3 frame generation compatibility. Disable this if the new submission logic causes performance regressions in a specific game.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "no_staggered_submit", ","),
        },
        "vkd3d_config_pipeline_library_app_cache": {
            "label": "Config: Pipeline Library App Cache",
            "description": "Enable application-managed pipeline library caching. Alternative to setting VKD3D_SHADER_CACHE_PATH=0 for applications that manage their own shader caches well.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "pipeline_library_app_cache", ","),
        },
        "vkd3d_config_breadcrumbs": {
            "label": "Config: Breadcrumbs Debug",
            "description": "Instrument command lists with VK_AMD_buffer_marker or VK_NV_device_checkpoints for GPU hang debugging. On GPU device lost or timeout, crash dumps are written to the log. For best results on RADV, also set RADV_DEBUG=syncshaders. Requires a non-release vkd3d-proton build with trace enabled.",
            "inputs": "value=on",
            "output": ("environment_variable", "VKD3D_CONFIG", "", "breadcrumbs", ","),
        },
        "vkd3d_shader_cache_path": {
            "label": "Shader Cache Path",
            "description": "Override the directory where vkd3d-proton.cache is stored. Set to 0 to disable the internal shader cache entirely (useful if the application manages its own pipeline cache via ID3D12PipelineLibrary).",
            "inputs": "0=disable, value=directory path",
            "output": ("environment_variable", "VKD3D_SHADER_CACHE_PATH", "", "", ""),
        },
        "vkd3d_debug": {
            "label": "Debug Log Level",
            "description": "Control vkd3d-proton log verbosity.",
            "inputs": "none=none, err=errors only, info=info, fixme=fixme, warn=warnings, trace=trace (verbose)",
            "output": ("environment_variable", "VKD3D_DEBUG", "", "", ""),
        },
        "vkd3d_shader_debug": {
            "label": "Shader Debug Log Level",
            "description": "Control debug log verbosity specifically for the vkd3d-proton shader compilers.",
            "inputs": "none=none, err=errors only, info=info, fixme=fixme, warn=warnings, trace=trace (verbose)",
            "output": ("environment_variable", "VKD3D_SHADER_DEBUG", "", "", ""),
        },
        "vkd3d_log_file": {
            "label": "Log File",
            "description": "Redirect VKD3D_DEBUG logging output to a file instead of stderr.",
            "inputs": "value=filesystem path (e.g. /tmp/vkd3d.log)",
            "output": ("environment_variable", "VKD3D_LOG_FILE", "", "", ""),
        },
        "vkd3d_shader_dump_path": {
            "label": "Shader Dump Path",
            "description": "Directory where shader bytecode is dumped. Files are saved as $hash.{spv,dxbc,dxil}. Clear the folder before dumping as existing files are not overwritten.",
            "inputs": "value=directory path",
            "output": ("environment_variable", "VKD3D_SHADER_DUMP_PATH", "", "", ""),
        },
        "vkd3d_shader_override": {
            "label": "Shader Override Path",
            "description": "Directory containing replacement SPIR-V shaders. If a file named $hash.spv exists in this directory and a pipeline uses that shader, the file will be used instead of the compiled one.",
            "inputs": "value=directory path",
            "output": ("environment_variable", "VKD3D_SHADER_OVERRIDE", "", "", ""),
        },
        "vkd3d_auto_capture_shader": {
            "label": "Auto Capture Shader (RenderDoc)",
            "description": "If set to a shader hash and the RenderDoc layer is enabled, vkd3d-proton will automatically trigger a capture when that specific shader is encountered.",
            "inputs": "value=shader hash",
            "output": ("environment_variable", "VKD3D_AUTO_CAPTURE_SHADER", "", "", ""),
        },
        "vkd3d_auto_capture_counts": {
            "label": "Auto Capture Counts (RenderDoc)",
            "description": "Comma-separated list of queue submission indices to auto-capture with RenderDoc (e.g. 0,4,10 captures the 1st, 5th, and 11th submissions). Set to -1 to capture the entire app runtime as one big capture.",
            "inputs": "value=comma-separated indices (e.g. 0,4,10) or -1 for all",
            "output": ("environment_variable", "VKD3D_AUTO_CAPTURE_COUNTS", "", "", ""),
        },
        "vkd3d_profile_path": {
            "label": "Profile Output Path",
            "description": "If profiling is enabled in the build (-Denable_profiling=true), write profiling binary blobs to this path prefix. The output file is ${VKD3D_PROFILE_PATH}.${pid}, analyzable with programs/vkd3d-profile.py.",
            "inputs": "value=path prefix (e.g. /tmp/vkd3d-profile)",
            "output": ("environment_variable", "VKD3D_PROFILE_PATH", "", "", ""),
        },
        "vkd3d_shader_debug_ring_size_log2": {
            "label": "Shader Debug Ring Size",
            "description": "Enable shader printf-style logging via a host-memory ring buffer. The value is the log2 of the buffer size in bytes (e.g. 28 = 256 MiB). Requires VK_KHR_buffer_device_address. Uses host memory only, not VRAM.",
            "inputs": "value=log2 of size (e.g. 28 for 256 MiB, 24 for 16 MiB)",
            "output": ("environment_variable", "VKD3D_SHADER_DEBUG_RING_SIZE_LOG2", "", "", ""),
        },
        "dxil_spirv_config_rdna3_workaround": {
            "label": "DXIL SPIRV RDNA3 Workaround",
            "description": "Workaround for graphical glitches when running FSR4 on RDNA3 GPUs in FP16 mode. Required alongside FSR4 Upgrade (PROTON_FSR4_UPGRADE) on RDNA3 hardware. Sets the wmma_rdna3_workaround flag in DXIL_SPIRV_CONFIG.",
            "inputs": "value=on",
            "output": ("environment_variable", "DXIL_SPIRV_CONFIG", "", "wmma_rdna3_workaround", ","),
        },
    }
